-- MySQL Script generated by MySQL Workbench
-- Tue Sep 25 12:46:57 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema comenta-ai
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema comenta-ai
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `comenta-ai` DEFAULT CHARACTER SET utf8 ;
USE `comenta-ai` ;

-- -----------------------------------------------------
-- Table `comenta-ai`.`alunos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `comenta-ai`.`alunos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NULL,
  `senha` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `comenta-ai`.`ies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `comenta-ai`.`ies` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `local` VARCHAR(45) NOT NULL,
  `media` DOUBLE NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `comenta-ai`.`avaliacoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `comenta-ai`.`avaliacoes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `pros` VARCHAR(1000) NULL,
  `contras` VARCHAR(1000) NULL,
  `conselho_direcao` VARCHAR(1000) NULL,
  `nota` DOUBLE NOT NULL,
  ` voltaria` VARCHAR(20) NOT NULL,
  `alunos_id` INT NOT NULL,
  `ies_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_avaliacoes_ies1_idx` (`ies_id` ASC),
  INDEX `fk_alunos_idx` (`alunos_id` ASC),
  CONSTRAINT `fk_alunos`
    FOREIGN KEY (`alunos_id`)
    REFERENCES `comenta-ai`.`alunos` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ies`
    FOREIGN KEY (`ies_id`)
    REFERENCES `comenta-ai`.`ies` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE USER 'root';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
