insert into cursos (nome) values ('Automation Specialist III');
insert into cursos (nome) values ('Assistant Media Planner');
insert into cursos (nome) values ('Graphic Designer');
insert into cursos (nome) values ('Accountant I');
insert into cursos (nome) values ('Software Consultant');
insert into cursos (nome) values ('Web Designer I');
insert into cursos (nome) values ('Health Coach III');
insert into cursos (nome) values ('Sales Representative');
insert into cursos (nome) values ('Structural Engineer');
insert into cursos (nome) values ('Internal Auditor');
insert into cursos (nome) values ('Graphic Designer');
insert into cursos (nome) values ('GIS Technical Architect');
insert into cursos (nome) values ('VP Product Management');
insert into cursos (nome) values ('Accountant III');
insert into cursos (nome) values ('Account Coordinator');
insert into cursos (nome) values ('Assistant Manager');
insert into cursos (nome) values ('Internal Auditor');
insert into cursos (nome) values ('Product Engineer');
insert into cursos (nome) values ('Executive Secretary');
insert into cursos (nome) values ('Software Engineer I');
insert into cursos (nome) values ('Programmer Analyst I');
insert into cursos (nome) values ('Statistician II');
insert into cursos (nome) values ('Sales Associate');
insert into cursos (nome) values ('Financial Advisor');
insert into cursos (nome) values ('Professor');
insert into cursos (nome) values ('Design Engineer');
insert into cursos (nome) values ('Geologist III');
insert into cursos (nome) values ('Occupational Therapist');
insert into cursos (nome) values ('Teacher');
insert into cursos (nome) values ('Social Worker');
insert into cursos (nome) values ('Editor');
insert into cursos (nome) values ('Engineer I');
insert into cursos (nome) values ('Editor');
insert into cursos (nome) values ('Environmental Tech');
insert into cursos (nome) values ('Environmental Specialist');
insert into cursos (nome) values ('Media Manager III');
insert into cursos (nome) values ('Tax Accountant');
insert into cursos (nome) values ('Graphic Designer');
insert into cursos (nome) values ('Senior Developer');
insert into cursos (nome) values ('Marketing Manager');
insert into cursos (nome) values ('Environmental Specialist');
insert into cursos (nome) values ('Financial Analyst');
insert into cursos (nome) values ('Associate Professor');
insert into cursos (nome) values ('Payment Adjustment Coordinator');
insert into cursos (nome) values ('Occupational Therapist');
insert into cursos (nome) values ('Tax Accountant');
insert into cursos (nome) values ('General Manager');
insert into cursos (nome) values ('Programmer II');
insert into cursos (nome) values ('Clinical Specialist');
insert into cursos (nome) values ('Engineer II');
insert into cursos (nome) values ('Health Coach II');
insert into cursos (nome) values ('Quality Engineer');
insert into cursos (nome) values ('Account Coordinator');
insert into cursos (nome) values ('Account Coordinator');
insert into cursos (nome) values ('Nurse Practicioner');
insert into cursos (nome) values ('Associate Professor');
insert into cursos (nome) values ('Analyst Programmer');
insert into cursos (nome) values ('Software Engineer I');
insert into cursos (nome) values ('Account Executive');
insert into cursos (nome) values ('Mechanical Systems Engineer');
insert into cursos (nome) values ('Web Developer IV');
insert into cursos (nome) values ('Accountant I');
insert into cursos (nome) values ('Developer IV');
insert into cursos (nome) values ('Professor');
insert into cursos (nome) values ('Staff Scientist');
insert into cursos (nome) values ('Desktop Support Technician');
insert into cursos (nome) values ('GIS Technical Architect');
insert into cursos (nome) values ('Assistant Professor');
insert into cursos (nome) values ('Paralegal');
insert into cursos (nome) values ('Professor');
insert into cursos (nome) values ('Compensation Analyst');
insert into cursos (nome) values ('Recruiting Manager');
insert into cursos (nome) values ('Web Designer I');
insert into cursos (nome) values ('Help Desk Operator');
insert into cursos (nome) values ('Administrative Assistant II');
insert into cursos (nome) values ('Quality Engineer');
insert into cursos (nome) values ('Safety Technician I');
insert into cursos (nome) values ('Assistant Professor');
insert into cursos (nome) values ('Physical Therapy Assistant');
insert into cursos (nome) values ('Nurse Practicioner');
insert into cursos (nome) values ('Graphic Designer');
insert into cursos (nome) values ('Actuary');
insert into cursos (nome) values ('Payment Adjustment Coordinator');
insert into cursos (nome) values ('Tax Accountant');
insert into cursos (nome) values ('Account Executive');
insert into cursos (nome) values ('Budget/Accounting Analyst I');
insert into cursos (nome) values ('Sales Associate');
insert into cursos (nome) values ('Physical Therapy Assistant');
insert into cursos (nome) values ('Director of Sales');
insert into cursos (nome) values ('Chemical Engineer');
insert into cursos (nome) values ('Nurse Practicioner');
insert into cursos (nome) values ('Information Systems Manager');
insert into cursos (nome) values ('Research Associate');
insert into cursos (nome) values ('Tax Accountant');
insert into cursos (nome) values ('Operator');
insert into cursos (nome) values ('Statistician II');
insert into cursos (nome) values ('Structural Engineer');
insert into cursos (nome) values ('General Manager');
insert into cursos (nome) values ('Safety Technician III');
insert into cursos (nome) values ('Technical Writer');
insert into cursos (nome) values ('Systems Administrator IV');
insert into cursos (nome) values ('Budget/Accounting Analyst III');
insert into cursos (nome) values ('Financial Analyst');
insert into cursos (nome) values ('Data Coordiator');
insert into cursos (nome) values ('Senior Cost Accountant');
insert into cursos (nome) values ('Analyst Programmer');
insert into cursos (nome) values ('Administrative Officer');
insert into cursos (nome) values ('Software Consultant');
insert into cursos (nome) values ('Financial Advisor');
insert into cursos (nome) values ('Clinical Specialist');
insert into cursos (nome) values ('Statistician I');
insert into cursos (nome) values ('Staff Accountant I');
insert into cursos (nome) values ('Programmer III');
insert into cursos (nome) values ('Software Consultant');
insert into cursos (nome) values ('Business Systems Development Analyst');
insert into cursos (nome) values ('Help Desk Technician');
insert into cursos (nome) values ('Speech Pathologist');
insert into cursos (nome) values ('Senior Quality Engineer');
insert into cursos (nome) values ('Information Systems Manager');
insert into cursos (nome) values ('Nurse Practicioner');
insert into cursos (nome) values ('Biostatistician I');
insert into cursos (nome) values ('Senior Quality Engineer');
insert into cursos (nome) values ('Systems Administrator II');
insert into cursos (nome) values ('Recruiting Manager');
insert into cursos (nome) values ('Assistant Media Planner');
insert into cursos (nome) values ('Developer IV');
insert into cursos (nome) values ('Marketing Assistant');
insert into cursos (nome) values ('Senior Quality Engineer');
insert into cursos (nome) values ('Software Consultant');
insert into cursos (nome) values ('Quality Engineer');
insert into cursos (nome) values ('Research Assistant II');
insert into cursos (nome) values ('Research Assistant III');
insert into cursos (nome) values ('Editor');
insert into cursos (nome) values ('Developer I');
insert into cursos (nome) values ('Internal Auditor');
insert into cursos (nome) values ('Research Nurse');
insert into cursos (nome) values ('Account Coordinator');
insert into cursos (nome) values ('Senior Sales Associate');
insert into cursos (nome) values ('Health Coach III');
insert into cursos (nome) values ('Legal Assistant');
insert into cursos (nome) values ('Research Assistant III');
insert into cursos (nome) values ('Speech Pathologist');
insert into cursos (nome) values ('VP Sales');
insert into cursos (nome) values ('Social Worker');
insert into cursos (nome) values ('Legal Assistant');
insert into cursos (nome) values ('Research Assistant II');
insert into cursos (nome) values ('Quality Control Specialist');
insert into cursos (nome) values ('Business Systems Development Analyst');
insert into cursos (nome) values ('Nurse Practicioner');
insert into cursos (nome) values ('Senior Quality Engineer');
insert into cursos (nome) values ('Research Nurse');
insert into cursos (nome) values ('Director of Sales');
insert into cursos (nome) values ('Administrative Assistant II');
insert into cursos (nome) values ('Pharmacist');
insert into cursos (nome) values ('Help Desk Operator');
insert into cursos (nome) values ('Project Manager');
insert into cursos (nome) values ('Senior Sales Associate');
insert into cursos (nome) values ('Clinical Specialist');
insert into cursos (nome) values ('VP Quality Control');
insert into cursos (nome) values ('Research Assistant I');
insert into cursos (nome) values ('Staff Scientist');
insert into cursos (nome) values ('Financial Advisor');
insert into cursos (nome) values ('Financial Analyst');
insert into cursos (nome) values ('Human Resources Assistant III');
insert into cursos (nome) values ('Mechanical Systems Engineer');
insert into cursos (nome) values ('Environmental Specialist');
insert into cursos (nome) values ('Cost Accountant');
insert into cursos (nome) values ('Computer Systems Analyst II');
insert into cursos (nome) values ('VP Sales');
insert into cursos (nome) values ('Registered Nurse');
insert into cursos (nome) values ('Senior Cost Accountant');
insert into cursos (nome) values ('Sales Associate');
insert into cursos (nome) values ('Senior Editor');
insert into cursos (nome) values ('Analog Circuit Design manager');
insert into cursos (nome) values ('Software Test Engineer I');
insert into cursos (nome) values ('Pharmacist');
insert into cursos (nome) values ('Office Assistant II');
insert into cursos (nome) values ('Executive Secretary');
insert into cursos (nome) values ('Editor');
insert into cursos (nome) values ('Analyst Programmer');
insert into cursos (nome) values ('Staff Scientist');
insert into cursos (nome) values ('Programmer Analyst I');
insert into cursos (nome) values ('Recruiter');
insert into cursos (nome) values ('Clinical Specialist');
insert into cursos (nome) values ('VP Sales');
insert into cursos (nome) values ('VP Accounting');
insert into cursos (nome) values ('Structural Engineer');
insert into cursos (nome) values ('Clinical Specialist');
insert into cursos (nome) values ('Community Outreach Specialist');
insert into cursos (nome) values ('Database Administrator I');
insert into cursos (nome) values ('Senior Editor');
insert into cursos (nome) values ('Software Engineer IV');
insert into cursos (nome) values ('Sales Associate');
insert into cursos (nome) values ('Staff Scientist');
insert into cursos (nome) values ('Physical Therapy Assistant');
insert into cursos (nome) values ('Chief Design Engineer');
insert into cursos (nome) values ('Geologist II');
insert into cursos (nome) values ('Help Desk Technician');
insert into cursos (nome) values ('Operator');
insert into cursos (nome) values ('Recruiter');
insert into cursos (nome) values ('Environmental Specialist');
insert into cursos (nome) values ('Assistant Media Planner');
insert into cursos (nome) values ('Statistician I');
insert into cursos (nome) values ('Media Manager II');
insert into cursos (nome) values ('Sales Associate');
insert into cursos (nome) values ('Chemical Engineer');
insert into cursos (nome) values ('Clinical Specialist');
insert into cursos (nome) values ('VP Accounting');
insert into cursos (nome) values ('Help Desk Technician');
insert into cursos (nome) values ('Legal Assistant');
insert into cursos (nome) values ('Budget/Accounting Analyst IV');
insert into cursos (nome) values ('Safety Technician II');
insert into cursos (nome) values ('Nurse Practicioner');
insert into cursos (nome) values ('Structural Analysis Engineer');
insert into cursos (nome) values ('Staff Accountant IV');
insert into cursos (nome) values ('Internal Auditor');
insert into cursos (nome) values ('Senior Sales Associate');
insert into cursos (nome) values ('Software Engineer I');
insert into cursos (nome) values ('Editor');
insert into cursos (nome) values ('Administrative Officer');
insert into cursos (nome) values ('Computer Systems Analyst I');
insert into cursos (nome) values ('Structural Analysis Engineer');
insert into cursos (nome) values ('Programmer Analyst III');
insert into cursos (nome) values ('Programmer III');
insert into cursos (nome) values ('Business Systems Development Analyst');
insert into cursos (nome) values ('Help Desk Technician');
insert into cursos (nome) values ('Budget/Accounting Analyst IV');
insert into cursos (nome) values ('Marketing Assistant');
insert into cursos (nome) values ('Software Engineer II');
insert into cursos (nome) values ('Chief Design Engineer');
insert into cursos (nome) values ('Cost Accountant');
insert into cursos (nome) values ('Analog Circuit Design manager');
insert into cursos (nome) values ('Administrative Officer');
insert into cursos (nome) values ('Administrative Officer');
insert into cursos (nome) values ('Occupational Therapist');
insert into cursos (nome) values ('Tax Accountant');
insert into cursos (nome) values ('Budget/Accounting Analyst I');
insert into cursos (nome) values ('Geologist II');
insert into cursos (nome) values ('Database Administrator IV');
insert into cursos (nome) values ('Civil Engineer');
insert into cursos (nome) values ('Research Associate');
insert into cursos (nome) values ('Senior Financial Analyst');
insert into cursos (nome) values ('General Manager');
insert into cursos (nome) values ('Director of Sales');
insert into cursos (nome) values ('Professor');
insert into cursos (nome) values ('Tax Accountant');
insert into cursos (nome) values ('Recruiter');
insert into cursos (nome) values ('Database Administrator II');
insert into cursos (nome) values ('Web Designer III');
insert into cursos (nome) values ('Director of Sales');
insert into cursos (nome) values ('Web Designer I');
insert into cursos (nome) values ('Financial Advisor');
insert into cursos (nome) values ('Programmer III');
insert into cursos (nome) values ('Database Administrator I');
insert into cursos (nome) values ('Occupational Therapist');
insert into cursos (nome) values ('Sales Representative');
insert into cursos (nome) values ('VP Sales');
insert into cursos (nome) values ('Analyst Programmer');
insert into cursos (nome) values ('Help Desk Technician');
insert into cursos (nome) values ('Librarian');
insert into cursos (nome) values ('Assistant Professor');
insert into cursos (nome) values ('Electrical Engineer');
insert into cursos (nome) values ('Tax Accountant');
insert into cursos (nome) values ('VP Accounting');
insert into cursos (nome) values ('Geological Engineer');
insert into cursos (nome) values ('VP Sales');
insert into cursos (nome) values ('Web Designer I');
insert into cursos (nome) values ('Desktop Support Technician');
insert into cursos (nome) values ('Administrative Officer');
insert into cursos (nome) values ('Assistant Professor');
insert into cursos (nome) values ('Graphic Designer');
insert into cursos (nome) values ('Staff Scientist');
insert into cursos (nome) values ('Sales Representative');
insert into cursos (nome) values ('Design Engineer');
insert into cursos (nome) values ('Registered Nurse');
insert into cursos (nome) values ('Financial Advisor');
insert into cursos (nome) values ('Design Engineer');
insert into cursos (nome) values ('Media Manager III');
insert into cursos (nome) values ('Administrative Officer');
insert into cursos (nome) values ('Food Chemist');
insert into cursos (nome) values ('Cost Accountant');
insert into cursos (nome) values ('Desktop Support Technician');
insert into cursos (nome) values ('Cost Accountant');
insert into cursos (nome) values ('Chief Design Engineer');
insert into cursos (nome) values ('Staff Scientist');
insert into cursos (nome) values ('Programmer Analyst III');
insert into cursos (nome) values ('Sales Representative');
insert into cursos (nome) values ('Dental Hygienist');
insert into cursos (nome) values ('Quality Engineer');
insert into cursos (nome) values ('Database Administrator I');
insert into cursos (nome) values ('Marketing Manager');
insert into cursos (nome) values ('Account Executive');
insert into cursos (nome) values ('Junior Executive');
insert into cursos (nome) values ('Product Engineer');
insert into cursos (nome) values ('Software Engineer I');
insert into cursos (nome) values ('Senior Editor');
insert into cursos (nome) values ('VP Accounting');
insert into cursos (nome) values ('Associate Professor');
insert into cursos (nome) values ('Community Outreach Specialist');
insert into cursos (nome) values ('Help Desk Operator');
insert into cursos (nome) values ('Director of Sales');
insert into cursos (nome) values ('Software Consultant');
insert into cursos (nome) values ('Environmental Tech');
insert into cursos (nome) values ('Technical Writer');
insert into cursos (nome) values ('Design Engineer');
insert into cursos (nome) values ('Administrative Officer');
insert into cursos (nome) values ('Director of Sales');
insert into cursos (nome) values ('Account Executive');
insert into cursos (nome) values ('Business Systems Development Analyst');
insert into cursos (nome) values ('Physical Therapy Assistant');
insert into cursos (nome) values ('Compensation Analyst');
insert into cursos (nome) values ('Software Engineer I');
insert into cursos (nome) values ('Business Systems Development Analyst');
insert into cursos (nome) values ('Environmental Tech');
insert into cursos (nome) values ('Design Engineer');
insert into cursos (nome) values ('Legal Assistant');
insert into cursos (nome) values ('Senior Cost Accountant');
insert into cursos (nome) values ('Systems Administrator I');
insert into cursos (nome) values ('Operator');
insert into cursos (nome) values ('Quality Engineer');
insert into cursos (nome) values ('Quality Engineer');
insert into cursos (nome) values ('Systems Administrator II');
insert into cursos (nome) values ('Structural Analysis Engineer');
insert into cursos (nome) values ('Executive Secretary');
insert into cursos (nome) values ('Software Consultant');
insert into cursos (nome) values ('Social Worker');
insert into cursos (nome) values ('Environmental Tech');
insert into cursos (nome) values ('Quality Control Specialist');
insert into cursos (nome) values ('Quality Engineer');
insert into cursos (nome) values ('Analyst Programmer');
insert into cursos (nome) values ('Help Desk Technician');
insert into cursos (nome) values ('Senior Sales Associate');
insert into cursos (nome) values ('Help Desk Technician');
insert into cursos (nome) values ('Engineer II');
insert into cursos (nome) values ('Human Resources Assistant IV');
insert into cursos (nome) values ('Executive Secretary');
insert into cursos (nome) values ('Financial Advisor');
insert into cursos (nome) values ('Operator');
insert into cursos (nome) values ('Senior Developer');
insert into cursos (nome) values ('Project Manager');
insert into cursos (nome) values ('Systems Administrator IV');
insert into cursos (nome) values ('Software Consultant');
insert into cursos (nome) values ('Senior Sales Associate');
insert into cursos (nome) values ('Budget/Accounting Analyst I');
insert into cursos (nome) values ('Research Nurse');
insert into cursos (nome) values ('Chief Design Engineer');
insert into cursos (nome) values ('Health Coach IV');
insert into cursos (nome) values ('Graphic Designer');
insert into cursos (nome) values ('Clinical Specialist');
insert into cursos (nome) values ('Compensation Analyst');
insert into cursos (nome) values ('Information Systems Manager');
insert into cursos (nome) values ('Nurse Practicioner');
insert into cursos (nome) values ('Automation Specialist IV');
insert into cursos (nome) values ('Pharmacist');
insert into cursos (nome) values ('Physical Therapy Assistant');
insert into cursos (nome) values ('Structural Engineer');
insert into cursos (nome) values ('Geological Engineer');
insert into cursos (nome) values ('Computer Systems Analyst III');
insert into cursos (nome) values ('Geologist IV');
insert into cursos (nome) values ('Accounting Assistant III');
insert into cursos (nome) values ('Engineer III');
insert into cursos (nome) values ('Technical Writer');
insert into cursos (nome) values ('VP Quality Control');
insert into cursos (nome) values ('Actuary');
insert into cursos (nome) values ('Account Executive');
insert into cursos (nome) values ('Assistant Media Planner');
insert into cursos (nome) values ('VP Quality Control');
insert into cursos (nome) values ('Registered Nurse');
insert into cursos (nome) values ('Recruiting Manager');
insert into cursos (nome) values ('Research Nurse');
insert into cursos (nome) values ('VP Product Management');
insert into cursos (nome) values ('Financial Advisor');
insert into cursos (nome) values ('Environmental Specialist');
insert into cursos (nome) values ('Assistant Media Planner');
insert into cursos (nome) values ('Geological Engineer');
insert into cursos (nome) values ('Senior Sales Associate');
insert into cursos (nome) values ('Budget/Accounting Analyst III');
insert into cursos (nome) values ('Accountant I');
insert into cursos (nome) values ('Web Designer I');
insert into cursos (nome) values ('VP Product Management');
insert into cursos (nome) values ('Civil Engineer');
insert into cursos (nome) values ('Financial Analyst');
insert into cursos (nome) values ('Environmental Specialist');
insert into cursos (nome) values ('Human Resources Manager');
insert into cursos (nome) values ('Recruiter');
insert into cursos (nome) values ('Financial Analyst');
insert into cursos (nome) values ('Senior Quality Engineer');
insert into cursos (nome) values ('Sales Associate');
insert into cursos (nome) values ('Administrative Assistant III');
insert into cursos (nome) values ('Registered Nurse');
insert into cursos (nome) values ('VP Product Management');
insert into cursos (nome) values ('Speech Pathologist');
insert into cursos (nome) values ('Media Manager III');
insert into cursos (nome) values ('Business Systems Development Analyst');
insert into cursos (nome) values ('Developer III');
insert into cursos (nome) values ('Junior Executive');
insert into cursos (nome) values ('Chief Design Engineer');
insert into cursos (nome) values ('Marketing Manager');
insert into cursos (nome) values ('Biostatistician IV');
insert into cursos (nome) values ('Account Representative IV');
insert into cursos (nome) values ('Payment Adjustment Coordinator');
insert into cursos (nome) values ('Teacher');
insert into cursos (nome) values ('Account Representative IV');
insert into cursos (nome) values ('Senior Financial Analyst');
insert into cursos (nome) values ('Account Coordinator');
insert into cursos (nome) values ('Electrical Engineer');
insert into cursos (nome) values ('Software Engineer III');
insert into cursos (nome) values ('Senior Editor');
insert into cursos (nome) values ('Tax Accountant');
insert into cursos (nome) values ('Developer IV');
insert into cursos (nome) values ('Cost Accountant');
insert into cursos (nome) values ('Recruiter');
insert into cursos (nome) values ('Budget/Accounting Analyst III');
insert into cursos (nome) values ('Accounting Assistant I');
insert into cursos (nome) values ('Media Manager IV');
insert into cursos (nome) values ('VP Marketing');
insert into cursos (nome) values ('Recruiter');
insert into cursos (nome) values ('Senior Developer');
insert into cursos (nome) values ('Administrative Assistant III');
insert into cursos (nome) values ('Senior Cost Accountant');
insert into cursos (nome) values ('Assistant Media Planner');
insert into cursos (nome) values ('Operator');
insert into cursos (nome) values ('General Manager');
insert into cursos (nome) values ('Environmental Tech');
insert into cursos (nome) values ('Database Administrator I');
insert into cursos (nome) values ('Office Assistant I');
insert into cursos (nome) values ('Civil Engineer');
insert into cursos (nome) values ('Accountant IV');
insert into cursos (nome) values ('Assistant Manager');
insert into cursos (nome) values ('Senior Editor');
insert into cursos (nome) values ('Nurse Practicioner');
insert into cursos (nome) values ('Civil Engineer');
insert into cursos (nome) values ('Project Manager');
insert into cursos (nome) values ('Senior Financial Analyst');
insert into cursos (nome) values ('Assistant Professor');
insert into cursos (nome) values ('Account Coordinator');
insert into cursos (nome) values ('GIS Technical Architect');
insert into cursos (nome) values ('Account Representative IV');
insert into cursos (nome) values ('Chief Design Engineer');
insert into cursos (nome) values ('Environmental Tech');
insert into cursos (nome) values ('Staff Scientist');
insert into cursos (nome) values ('Research Associate');
insert into cursos (nome) values ('Administrative Officer');
insert into cursos (nome) values ('Accounting Assistant I');
insert into cursos (nome) values ('Research Associate');
insert into cursos (nome) values ('Automation Specialist IV');
insert into cursos (nome) values ('Analog Circuit Design manager');
insert into cursos (nome) values ('Social Worker');
insert into cursos (nome) values ('Senior Financial Analyst');
insert into cursos (nome) values ('Help Desk Operator');
insert into cursos (nome) values ('Assistant Professor');
insert into cursos (nome) values ('Staff Accountant I');
insert into cursos (nome) values ('Account Coordinator');
insert into cursos (nome) values ('Nuclear Power Engineer');
insert into cursos (nome) values ('Software Engineer IV');
insert into cursos (nome) values ('Assistant Manager');
insert into cursos (nome) values ('Budget/Accounting Analyst IV');
insert into cursos (nome) values ('Librarian');
insert into cursos (nome) values ('Cost Accountant');
insert into cursos (nome) values ('Office Assistant IV');
insert into cursos (nome) values ('Help Desk Technician');
insert into cursos (nome) values ('Sales Representative');
insert into cursos (nome) values ('Financial Analyst');
insert into cursos (nome) values ('Assistant Media Planner');
insert into cursos (nome) values ('Occupational Therapist');
insert into cursos (nome) values ('VP Accounting');
insert into cursos (nome) values ('General Manager');
insert into cursos (nome) values ('Recruiter');
insert into cursos (nome) values ('Senior Financial Analyst');
insert into cursos (nome) values ('Project Manager');
insert into cursos (nome) values ('Account Representative I');
insert into cursos (nome) values ('Assistant Professor');
insert into cursos (nome) values ('Community Outreach Specialist');
insert into cursos (nome) values ('Recruiting Manager');
insert into cursos (nome) values ('Design Engineer');
insert into cursos (nome) values ('Engineer IV');
insert into cursos (nome) values ('Senior Developer');
insert into cursos (nome) values ('Dental Hygienist');
insert into cursos (nome) values ('Senior Cost Accountant');
insert into cursos (nome) values ('Structural Analysis Engineer');
insert into cursos (nome) values ('Human Resources Assistant III');
insert into cursos (nome) values ('Programmer Analyst IV');
insert into cursos (nome) values ('Civil Engineer');
insert into cursos (nome) values ('Database Administrator I');
insert into cursos (nome) values ('Research Assistant I');
insert into cursos (nome) values ('Senior Editor');
insert into cursos (nome) values ('Compensation Analyst');
insert into cursos (nome) values ('Assistant Media Planner');
insert into cursos (nome) values ('Programmer Analyst II');
insert into cursos (nome) values ('Research Nurse');
insert into cursos (nome) values ('Human Resources Manager');
insert into cursos (nome) values ('Senior Financial Analyst');
insert into cursos (nome) values ('Administrative Assistant I');
insert into cursos (nome) values ('Project Manager');
insert into cursos (nome) values ('Junior Executive');
insert into cursos (nome) values ('Accountant III');
insert into cursos (nome) values ('Analyst Programmer');
insert into cursos (nome) values ('Project Manager');
insert into cursos (nome) values ('Computer Systems Analyst I');
insert into cursos (nome) values ('Civil Engineer');
insert into cursos (nome) values ('Statistician IV');
insert into cursos (nome) values ('VP Marketing');
insert into cursos (nome) values ('Assistant Media Planner');
insert into cursos (nome) values ('Biostatistician II');
insert into cursos (nome) values ('Senior Developer');
insert into cursos (nome) values ('Web Designer I');
insert into cursos (nome) values ('Nurse Practicioner');
insert into cursos (nome) values ('VP Accounting');
insert into cursos (nome) values ('Professor');
insert into cursos (nome) values ('Quality Control Specialist');
insert into cursos (nome) values ('Statistician I');
insert into cursos (nome) values ('Physical Therapy Assistant');
insert into cursos (nome) values ('Accountant IV');
insert into cursos (nome) values ('Sales Representative');
insert into cursos (nome) values ('Programmer Analyst II');
insert into cursos (nome) values ('Staff Scientist');
insert into cursos (nome) values ('Dental Hygienist');
insert into cursos (nome) values ('Mechanical Systems Engineer');
insert into cursos (nome) values ('Assistant Professor');
insert into cursos (nome) values ('Cost Accountant');
insert into cursos (nome) values ('Compensation Analyst');
insert into cursos (nome) values ('Design Engineer');
insert into cursos (nome) values ('VP Accounting');
insert into cursos (nome) values ('VP Sales');
insert into cursos (nome) values ('Sales Representative');
insert into cursos (nome) values ('Programmer III');
insert into cursos (nome) values ('Actuary');
insert into cursos (nome) values ('Junior Executive');
insert into cursos (nome) values ('Food Chemist');
insert into cursos (nome) values ('Graphic Designer');
insert into cursos (nome) values ('Senior Cost Accountant');
insert into cursos (nome) values ('Social Worker');
insert into cursos (nome) values ('Sales Representative');
insert into cursos (nome) values ('Administrative Assistant II');
insert into cursos (nome) values ('Computer Systems Analyst III');
insert into cursos (nome) values ('Sales Associate');
insert into cursos (nome) values ('Chemical Engineer');
insert into cursos (nome) values ('Food Chemist');
insert into cursos (nome) values ('Web Developer II');
insert into cursos (nome) values ('Computer Systems Analyst IV');
insert into cursos (nome) values ('Analyst Programmer');
insert into cursos (nome) values ('Account Representative IV');
insert into cursos (nome) values ('Software Engineer I');
insert into cursos (nome) values ('Software Test Engineer III');
insert into cursos (nome) values ('VP Accounting');
insert into cursos (nome) values ('Sales Associate');
insert into cursos (nome) values ('Research Associate');
insert into cursos (nome) values ('Chemical Engineer');
insert into cursos (nome) values ('Financial Analyst');
insert into cursos (nome) values ('VP Quality Control');
insert into cursos (nome) values ('Speech Pathologist');
insert into cursos (nome) values ('Senior Quality Engineer');
insert into cursos (nome) values ('Professor');
insert into cursos (nome) values ('Environmental Tech');
insert into cursos (nome) values ('Human Resources Assistant IV');
insert into cursos (nome) values ('Accounting Assistant I');
insert into cursos (nome) values ('Nurse Practicioner');
insert into cursos (nome) values ('Quality Control Specialist');
insert into cursos (nome) values ('Geological Engineer');
insert into cursos (nome) values ('Payment Adjustment Coordinator');
insert into cursos (nome) values ('Systems Administrator II');
insert into cursos (nome) values ('Food Chemist');
insert into cursos (nome) values ('Systems Administrator III');
insert into cursos (nome) values ('Editor');
insert into cursos (nome) values ('VP Marketing');
insert into cursos (nome) values ('Operator');
insert into cursos (nome) values ('Paralegal');
insert into cursos (nome) values ('Software Test Engineer III');
insert into cursos (nome) values ('Desktop Support Technician');
insert into cursos (nome) values ('Executive Secretary');
insert into cursos (nome) values ('Actuary');
insert into cursos (nome) values ('Office Assistant IV');
insert into cursos (nome) values ('Quality Engineer');
insert into cursos (nome) values ('Administrative Officer');
insert into cursos (nome) values ('Actuary');
insert into cursos (nome) values ('Structural Analysis Engineer');
insert into cursos (nome) values ('Senior Quality Engineer');
insert into cursos (nome) values ('Research Associate');
insert into cursos (nome) values ('General Manager');
insert into cursos (nome) values ('Product Engineer');
insert into cursos (nome) values ('Human Resources Assistant IV');
insert into cursos (nome) values ('Accounting Assistant II');
insert into cursos (nome) values ('Computer Systems Analyst III');
insert into cursos (nome) values ('Mechanical Systems Engineer');
insert into cursos (nome) values ('Nuclear Power Engineer');
insert into cursos (nome) values ('Assistant Media Planner');
insert into cursos (nome) values ('Teacher');
insert into cursos (nome) values ('Statistician IV');
insert into cursos (nome) values ('Data Coordiator');
insert into cursos (nome) values ('Account Representative I');
insert into cursos (nome) values ('Pharmacist');
insert into cursos (nome) values ('Marketing Manager');
insert into cursos (nome) values ('Staff Accountant I');
insert into cursos (nome) values ('Automation Specialist III');
insert into cursos (nome) values ('Physical Therapy Assistant');
insert into cursos (nome) values ('Environmental Tech');
insert into cursos (nome) values ('Design Engineer');
insert into cursos (nome) values ('Environmental Tech');
insert into cursos (nome) values ('Health Coach IV');
insert into cursos (nome) values ('Associate Professor');
insert into cursos (nome) values ('Account Representative II');
insert into cursos (nome) values ('Product Engineer');
insert into cursos (nome) values ('Junior Executive');
insert into cursos (nome) values ('Community Outreach Specialist');
insert into cursos (nome) values ('Internal Auditor');
insert into cursos (nome) values ('Geologist I');
insert into cursos (nome) values ('Social Worker');
insert into cursos (nome) values ('Senior Sales Associate');
insert into cursos (nome) values ('Database Administrator I');
insert into cursos (nome) values ('Financial Analyst');
insert into cursos (nome) values ('Human Resources Manager');
insert into cursos (nome) values ('Food Chemist');
insert into cursos (nome) values ('Web Developer I');
insert into cursos (nome) values ('Software Test Engineer II');
insert into cursos (nome) values ('Editor');
insert into cursos (nome) values ('Senior Developer');
insert into cursos (nome) values ('Marketing Assistant');
insert into cursos (nome) values ('Occupational Therapist');
insert into cursos (nome) values ('Librarian');
insert into cursos (nome) values ('Research Associate');
insert into cursos (nome) values ('Associate Professor');
insert into cursos (nome) values ('Account Representative III');
insert into cursos (nome) values ('Paralegal');
insert into cursos (nome) values ('VP Sales');
insert into cursos (nome) values ('Programmer III');
insert into cursos (nome) values ('Programmer I');
insert into cursos (nome) values ('Research Assistant I');
insert into cursos (nome) values ('Editor');
insert into cursos (nome) values ('Tax Accountant');
insert into cursos (nome) values ('Quality Control Specialist');
insert into cursos (nome) values ('VP Product Management');
insert into cursos (nome) values ('VP Quality Control');
insert into cursos (nome) values ('Pharmacist');
insert into cursos (nome) values ('Software Consultant');
insert into cursos (nome) values ('Research Assistant IV');
insert into cursos (nome) values ('VP Accounting');
insert into cursos (nome) values ('Librarian');
insert into cursos (nome) values ('Quality Control Specialist');
insert into cursos (nome) values ('Social Worker');
insert into cursos (nome) values ('Programmer I');
insert into cursos (nome) values ('Biostatistician I');
insert into cursos (nome) values ('Assistant Media Planner');
insert into cursos (nome) values ('Systems Administrator IV');
insert into cursos (nome) values ('Programmer Analyst II');
insert into cursos (nome) values ('Programmer Analyst III');
insert into cursos (nome) values ('Analog Circuit Design manager');
insert into cursos (nome) values ('Compensation Analyst');
insert into cursos (nome) values ('Pharmacist');
insert into cursos (nome) values ('Speech Pathologist');
insert into cursos (nome) values ('Occupational Therapist');
insert into cursos (nome) values ('Structural Analysis Engineer');
insert into cursos (nome) values ('Quality Control Specialist');
insert into cursos (nome) values ('Chief Design Engineer');
insert into cursos (nome) values ('Technical Writer');
insert into cursos (nome) values ('Internal Auditor');
insert into cursos (nome) values ('Assistant Media Planner');
insert into cursos (nome) values ('Compensation Analyst');
insert into cursos (nome) values ('Mechanical Systems Engineer');
insert into cursos (nome) values ('Food Chemist');
insert into cursos (nome) values ('Associate Professor');
insert into cursos (nome) values ('Research Assistant I');
insert into cursos (nome) values ('Mechanical Systems Engineer');
insert into cursos (nome) values ('Senior Financial Analyst');
insert into cursos (nome) values ('Product Engineer');
insert into cursos (nome) values ('Social Worker');
insert into cursos (nome) values ('Occupational Therapist');
insert into cursos (nome) values ('Web Developer III');
insert into cursos (nome) values ('Statistician II');
insert into cursos (nome) values ('Graphic Designer');
insert into cursos (nome) values ('Quality Control Specialist');
insert into cursos (nome) values ('Structural Analysis Engineer');
insert into cursos (nome) values ('Sales Representative');
insert into cursos (nome) values ('Tax Accountant');
insert into cursos (nome) values ('Account Representative IV');
insert into cursos (nome) values ('Actuary');
insert into cursos (nome) values ('Administrative Assistant I');
insert into cursos (nome) values ('Chief Design Engineer');
insert into cursos (nome) values ('Design Engineer');
insert into cursos (nome) values ('Project Manager');
insert into cursos (nome) values ('Geological Engineer');
insert into cursos (nome) values ('Recruiter');
insert into cursos (nome) values ('Research Assistant IV');
insert into cursos (nome) values ('Geological Engineer');
insert into cursos (nome) values ('Financial Advisor');
insert into cursos (nome) values ('Software Engineer III');
insert into cursos (nome) values ('Senior Developer');
insert into cursos (nome) values ('Marketing Manager');
insert into cursos (nome) values ('Senior Developer');
insert into cursos (nome) values ('Editor');
insert into cursos (nome) values ('Nurse Practicioner');
insert into cursos (nome) values ('Software Engineer III');
insert into cursos (nome) values ('Occupational Therapist');
insert into cursos (nome) values ('Nurse Practicioner');
insert into cursos (nome) values ('Pharmacist');
insert into cursos (nome) values ('Social Worker');
insert into cursos (nome) values ('Occupational Therapist');
insert into cursos (nome) values ('Computer Systems Analyst II');
insert into cursos (nome) values ('Chemical Engineer');
insert into cursos (nome) values ('Geologist III');
insert into cursos (nome) values ('Physical Therapy Assistant');
insert into cursos (nome) values ('Research Associate');
insert into cursos (nome) values ('Analog Circuit Design manager');
insert into cursos (nome) values ('Compensation Analyst');
insert into cursos (nome) values ('Senior Sales Associate');
insert into cursos (nome) values ('Operator');
insert into cursos (nome) values ('Actuary');
insert into cursos (nome) values ('Community Outreach Specialist');
insert into cursos (nome) values ('Software Engineer II');
insert into cursos (nome) values ('Food Chemist');
insert into cursos (nome) values ('Sales Representative');
insert into cursos (nome) values ('Biostatistician III');
insert into cursos (nome) values ('Senior Editor');
insert into cursos (nome) values ('Quality Engineer');
insert into cursos (nome) values ('Cost Accountant');
insert into cursos (nome) values ('Pharmacist');
insert into cursos (nome) values ('Director of Sales');
insert into cursos (nome) values ('Budget/Accounting Analyst III');
insert into cursos (nome) values ('Legal Assistant');
insert into cursos (nome) values ('Technical Writer');
insert into cursos (nome) values ('General Manager');
insert into cursos (nome) values ('Human Resources Assistant II');
insert into cursos (nome) values ('Analog Circuit Design manager');
insert into cursos (nome) values ('Data Coordiator');
insert into cursos (nome) values ('Programmer I');
insert into cursos (nome) values ('Product Engineer');
insert into cursos (nome) values ('Internal Auditor');
insert into cursos (nome) values ('Programmer III');
insert into cursos (nome) values ('Nuclear Power Engineer');
insert into cursos (nome) values ('Executive Secretary');
insert into cursos (nome) values ('VP Product Management');
insert into cursos (nome) values ('VP Accounting');
insert into cursos (nome) values ('Research Assistant IV');
insert into cursos (nome) values ('Senior Editor');
insert into cursos (nome) values ('Software Consultant');
insert into cursos (nome) values ('Account Representative II');
insert into cursos (nome) values ('Geological Engineer');
insert into cursos (nome) values ('Project Manager');
insert into cursos (nome) values ('Graphic Designer');
insert into cursos (nome) values ('Assistant Manager');
insert into cursos (nome) values ('Analog Circuit Design manager');
insert into cursos (nome) values ('Analog Circuit Design manager');
insert into cursos (nome) values ('Editor');
insert into cursos (nome) values ('Developer I');
insert into cursos (nome) values ('Assistant Professor');
insert into cursos (nome) values ('Financial Analyst');
insert into cursos (nome) values ('Junior Executive');
insert into cursos (nome) values ('Social Worker');
insert into cursos (nome) values ('Media Manager II');
insert into cursos (nome) values ('Analog Circuit Design manager');
insert into cursos (nome) values ('Nurse');
insert into cursos (nome) values ('Nurse Practicioner');
insert into cursos (nome) values ('Analyst Programmer');
insert into cursos (nome) values ('Software Test Engineer I');
insert into cursos (nome) values ('Human Resources Manager');
insert into cursos (nome) values ('Research Nurse');
insert into cursos (nome) values ('Graphic Designer');
insert into cursos (nome) values ('Nurse Practicioner');
insert into cursos (nome) values ('Desktop Support Technician');
insert into cursos (nome) values ('Automation Specialist IV');
insert into cursos (nome) values ('Technical Writer');
insert into cursos (nome) values ('Office Assistant I');
insert into cursos (nome) values ('Account Executive');
insert into cursos (nome) values ('Chief Design Engineer');
insert into cursos (nome) values ('VP Sales');
insert into cursos (nome) values ('Recruiting Manager');
insert into cursos (nome) values ('Assistant Media Planner');
insert into cursos (nome) values ('Nurse Practicioner');
insert into cursos (nome) values ('Pharmacist');
insert into cursos (nome) values ('Junior Executive');
insert into cursos (nome) values ('Staff Scientist');
insert into cursos (nome) values ('Biostatistician I');
insert into cursos (nome) values ('Food Chemist');
insert into cursos (nome) values ('Senior Developer');
insert into cursos (nome) values ('Biostatistician III');
insert into cursos (nome) values ('Safety Technician III');
insert into cursos (nome) values ('Senior Developer');
insert into cursos (nome) values ('Mechanical Systems Engineer');
insert into cursos (nome) values ('Design Engineer');
insert into cursos (nome) values ('Analog Circuit Design manager');
insert into cursos (nome) values ('Quality Control Specialist');
insert into cursos (nome) values ('Sales Representative');
insert into cursos (nome) values ('Accountant IV');
insert into cursos (nome) values ('Analog Circuit Design manager');
insert into cursos (nome) values ('Office Assistant III');
insert into cursos (nome) values ('Professor');
insert into cursos (nome) values ('Occupational Therapist');
insert into cursos (nome) values ('Recruiter');
insert into cursos (nome) values ('Environmental Specialist');
insert into cursos (nome) values ('Financial Analyst');
insert into cursos (nome) values ('Social Worker');
insert into cursos (nome) values ('Speech Pathologist');
insert into cursos (nome) values ('Librarian');
insert into cursos (nome) values ('Accounting Assistant III');
insert into cursos (nome) values ('Account Representative II');
insert into cursos (nome) values ('Junior Executive');
insert into cursos (nome) values ('Associate Professor');
insert into cursos (nome) values ('Chemical Engineer');
insert into cursos (nome) values ('Database Administrator IV');
insert into cursos (nome) values ('Tax Accountant');
insert into cursos (nome) values ('Assistant Professor');
insert into cursos (nome) values ('Registered Nurse');
insert into cursos (nome) values ('Civil Engineer');
insert into cursos (nome) values ('VP Accounting');
insert into cursos (nome) values ('Pharmacist');
insert into cursos (nome) values ('Web Designer IV');
insert into cursos (nome) values ('Analyst Programmer');
insert into cursos (nome) values ('Staff Accountant II');
insert into cursos (nome) values ('Research Associate');
insert into cursos (nome) values ('VP Product Management');
insert into cursos (nome) values ('Software Consultant');
insert into cursos (nome) values ('Occupational Therapist');
insert into cursos (nome) values ('Nurse Practicioner');
insert into cursos (nome) values ('Biostatistician I');
insert into cursos (nome) values ('Civil Engineer');
insert into cursos (nome) values ('Editor');
insert into cursos (nome) values ('Editor');
insert into cursos (nome) values ('Database Administrator II');
insert into cursos (nome) values ('Mechanical Systems Engineer');
insert into cursos (nome) values ('Assistant Manager');
insert into cursos (nome) values ('Teacher');
insert into cursos (nome) values ('Financial Advisor');
insert into cursos (nome) values ('Administrative Assistant III');
insert into cursos (nome) values ('Project Manager');
insert into cursos (nome) values ('Software Engineer IV');
insert into cursos (nome) values ('Internal Auditor');
insert into cursos (nome) values ('Director of Sales');
insert into cursos (nome) values ('Account Coordinator');
insert into cursos (nome) values ('Operator');
insert into cursos (nome) values ('Structural Analysis Engineer');
insert into cursos (nome) values ('Tax Accountant');
insert into cursos (nome) values ('Help Desk Technician');
insert into cursos (nome) values ('Quality Engineer');
insert into cursos (nome) values ('Payment Adjustment Coordinator');
insert into cursos (nome) values ('Structural Analysis Engineer');
insert into cursos (nome) values ('Registered Nurse');
insert into cursos (nome) values ('Software Engineer II');
insert into cursos (nome) values ('Executive Secretary');
insert into cursos (nome) values ('Business Systems Development Analyst');
insert into cursos (nome) values ('Programmer Analyst II');
insert into cursos (nome) values ('Staff Accountant III');
insert into cursos (nome) values ('Legal Assistant');
insert into cursos (nome) values ('Programmer II');
insert into cursos (nome) values ('Account Executive');
insert into cursos (nome) values ('Analyst Programmer');
insert into cursos (nome) values ('VP Marketing');
insert into cursos (nome) values ('Research Assistant IV');
insert into cursos (nome) values ('Social Worker');
insert into cursos (nome) values ('Structural Engineer');
insert into cursos (nome) values ('Associate Professor');
insert into cursos (nome) values ('Analyst Programmer');
insert into cursos (nome) values ('Mechanical Systems Engineer');
insert into cursos (nome) values ('Registered Nurse');
insert into cursos (nome) values ('Research Assistant II');
insert into cursos (nome) values ('Occupational Therapist');
insert into cursos (nome) values ('Design Engineer');
insert into cursos (nome) values ('Food Chemist');
insert into cursos (nome) values ('Occupational Therapist');
insert into cursos (nome) values ('Geologist I');
insert into cursos (nome) values ('Recruiter');
insert into cursos (nome) values ('Quality Control Specialist');
insert into cursos (nome) values ('Graphic Designer');
insert into cursos (nome) values ('Internal Auditor');
insert into cursos (nome) values ('Quality Control Specialist');
insert into cursos (nome) values ('Software Engineer I');
insert into cursos (nome) values ('Social Worker');
insert into cursos (nome) values ('Senior Sales Associate');
insert into cursos (nome) values ('Mechanical Systems Engineer');
insert into cursos (nome) values ('Community Outreach Specialist');
insert into cursos (nome) values ('Help Desk Technician');
insert into cursos (nome) values ('Executive Secretary');
insert into cursos (nome) values ('Structural Engineer');
insert into cursos (nome) values ('Web Designer I');
insert into cursos (nome) values ('Geologist III');
insert into cursos (nome) values ('Nurse');
insert into cursos (nome) values ('Senior Cost Accountant');
insert into cursos (nome) values ('Physical Therapy Assistant');
insert into cursos (nome) values ('Structural Engineer');
insert into cursos (nome) values ('Marketing Manager');
insert into cursos (nome) values ('Assistant Professor');
insert into cursos (nome) values ('Internal Auditor');
insert into cursos (nome) values ('Operator');
insert into cursos (nome) values ('Systems Administrator I');
insert into cursos (nome) values ('Legal Assistant');
insert into cursos (nome) values ('Assistant Media Planner');
insert into cursos (nome) values ('Web Designer IV');
insert into cursos (nome) values ('Environmental Specialist');
insert into cursos (nome) values ('Sales Representative');
insert into cursos (nome) values ('Technical Writer');
insert into cursos (nome) values ('Media Manager I');
insert into cursos (nome) values ('Help Desk Technician');
insert into cursos (nome) values ('Financial Analyst');
insert into cursos (nome) values ('Operator');
insert into cursos (nome) values ('Account Executive');
insert into cursos (nome) values ('Sales Associate');
insert into cursos (nome) values ('Recruiter');
insert into cursos (nome) values ('Product Engineer');
insert into cursos (nome) values ('Database Administrator I');
insert into cursos (nome) values ('Marketing Manager');
insert into cursos (nome) values ('Administrative Assistant IV');
insert into cursos (nome) values ('Occupational Therapist');
insert into cursos (nome) values ('Teacher');
insert into cursos (nome) values ('Sales Associate');
insert into cursos (nome) values ('Budget/Accounting Analyst I');
insert into cursos (nome) values ('Chief Design Engineer');
insert into cursos (nome) values ('Software Engineer I');
insert into cursos (nome) values ('Senior Financial Analyst');
insert into cursos (nome) values ('Senior Developer');
insert into cursos (nome) values ('Senior Cost Accountant');
insert into cursos (nome) values ('Geological Engineer');
insert into cursos (nome) values ('Accountant II');
insert into cursos (nome) values ('Account Representative III');
insert into cursos (nome) values ('Budget/Accounting Analyst I');
insert into cursos (nome) values ('Paralegal');
insert into cursos (nome) values ('Occupational Therapist');
insert into cursos (nome) values ('Biostatistician III');
insert into cursos (nome) values ('Research Associate');
insert into cursos (nome) values ('GIS Technical Architect');
insert into cursos (nome) values ('Mechanical Systems Engineer');
insert into cursos (nome) values ('Mechanical Systems Engineer');
insert into cursos (nome) values ('Internal Auditor');
insert into cursos (nome) values ('Physical Therapy Assistant');
insert into cursos (nome) values ('Registered Nurse');
insert into cursos (nome) values ('Help Desk Technician');
insert into cursos (nome) values ('Programmer Analyst III');
insert into cursos (nome) values ('Senior Cost Accountant');
insert into cursos (nome) values ('Pharmacist');
insert into cursos (nome) values ('VP Quality Control');
insert into cursos (nome) values ('Paralegal');
insert into cursos (nome) values ('Database Administrator III');
insert into cursos (nome) values ('Help Desk Operator');
insert into cursos (nome) values ('Recruiting Manager');
insert into cursos (nome) values ('Marketing Manager');
insert into cursos (nome) values ('Food Chemist');
insert into cursos (nome) values ('Software Test Engineer III');
insert into cursos (nome) values ('Administrative Officer');
insert into cursos (nome) values ('Electrical Engineer');
insert into cursos (nome) values ('Nuclear Power Engineer');
insert into cursos (nome) values ('Geological Engineer');
insert into cursos (nome) values ('Recruiter');
insert into cursos (nome) values ('Research Associate');
insert into cursos (nome) values ('VP Product Management');
insert into cursos (nome) values ('Human Resources Assistant II');
insert into cursos (nome) values ('Teacher');
insert into cursos (nome) values ('Paralegal');
insert into cursos (nome) values ('Structural Analysis Engineer');
insert into cursos (nome) values ('Account Representative I');
insert into cursos (nome) values ('Electrical Engineer');
insert into cursos (nome) values ('Computer Systems Analyst II');
insert into cursos (nome) values ('Accountant IV');
insert into cursos (nome) values ('Occupational Therapist');
insert into cursos (nome) values ('Senior Financial Analyst');
insert into cursos (nome) values ('Software Test Engineer III');
insert into cursos (nome) values ('VP Product Management');
insert into cursos (nome) values ('Data Coordiator');
insert into cursos (nome) values ('Food Chemist');
insert into cursos (nome) values ('Community Outreach Specialist');
insert into cursos (nome) values ('Database Administrator II');
insert into cursos (nome) values ('Web Designer III');
insert into cursos (nome) values ('Tax Accountant');
insert into cursos (nome) values ('Systems Administrator IV');
insert into cursos (nome) values ('Web Developer III');
insert into cursos (nome) values ('Internal Auditor');
insert into cursos (nome) values ('Staff Accountant IV');
insert into cursos (nome) values ('Safety Technician IV');
insert into cursos (nome) values ('Systems Administrator IV');
insert into cursos (nome) values ('Accountant I');
insert into cursos (nome) values ('Design Engineer');
insert into cursos (nome) values ('Accounting Assistant IV');
insert into cursos (nome) values ('Project Manager');
insert into cursos (nome) values ('VP Quality Control');
insert into cursos (nome) values ('Nurse');
insert into cursos (nome) values ('Accounting Assistant I');
insert into cursos (nome) values ('VP Marketing');
insert into cursos (nome) values ('Chemical Engineer');
insert into cursos (nome) values ('Chemical Engineer');
insert into cursos (nome) values ('Mechanical Systems Engineer');
insert into cursos (nome) values ('Food Chemist');
insert into cursos (nome) values ('Assistant Professor');
insert into cursos (nome) values ('Food Chemist');
insert into cursos (nome) values ('Statistician III');
insert into cursos (nome) values ('Automation Specialist II');
insert into cursos (nome) values ('Associate Professor');
insert into cursos (nome) values ('General Manager');
insert into cursos (nome) values ('Structural Engineer');
insert into cursos (nome) values ('Marketing Manager');
insert into cursos (nome) values ('Assistant Professor');
insert into cursos (nome) values ('Programmer Analyst II');
insert into cursos (nome) values ('Associate Professor');
insert into cursos (nome) values ('Sales Representative');
insert into cursos (nome) values ('Automation Specialist I');
insert into cursos (nome) values ('Analog Circuit Design manager');
insert into cursos (nome) values ('Design Engineer');
insert into cursos (nome) values ('Account Representative III');
insert into cursos (nome) values ('Account Coordinator');
insert into cursos (nome) values ('Desktop Support Technician');
insert into cursos (nome) values ('Compensation Analyst');
insert into cursos (nome) values ('Speech Pathologist');
insert into cursos (nome) values ('Sales Representative');
insert into cursos (nome) values ('Community Outreach Specialist');
insert into cursos (nome) values ('VP Product Management');
