insert into ies (nome, local, media) values ('Purdy, King and Nader', 'Brazil', 22.45);
insert into ies (nome, local, media) values ('Hahn-Reilly', 'Brazil', 58.69);
insert into ies (nome, local, media) values ('McDermott-Russel', 'Brazil', 89.24);
insert into ies (nome, local, media) values ('Rau, Bartell and Murphy', 'Brazil', 31.55);
insert into ies (nome, local, media) values ('Hoeger, Ondricka and Smitham', 'Brazil', 43.34);
insert into ies (nome, local, media) values ('Strosin and Sons', 'Brazil', 88.51);
insert into ies (nome, local, media) values ('Considine-Morissette', 'Brazil', 99.54);
insert into ies (nome, local, media) values ('Bernhard Inc', 'Brazil', 45.74);
insert into ies (nome, local, media) values ('Bartell-Bailey', 'Brazil', 10.36);
insert into ies (nome, local, media) values ('Lang, Kuvalis and Schimmel', 'Brazil', 80.71);
insert into ies (nome, local, media) values ('Leffler and Sons', 'Brazil', 95.12);
insert into ies (nome, local, media) values ('Skiles-Ullrich', 'Brazil', 22.55);
insert into ies (nome, local, media) values ('Murray, Lesch and Kozey', 'Brazil', 63.17);
insert into ies (nome, local, media) values ('Leffler-Kertzmann', 'Brazil', 25.3);
insert into ies (nome, local, media) values ('Wolf, Hartmann and Christiansen', 'Brazil', 87.82);
insert into ies (nome, local, media) values ('Schultz-Grant', 'Brazil', 82.54);
insert into ies (nome, local, media) values ('Greenholt and Sons', 'Brazil', 37.0);
insert into ies (nome, local, media) values ('Weimann LLC', 'Brazil', 84.45);
insert into ies (nome, local, media) values ('Parisian-Littel', 'Brazil', 28.51);
insert into ies (nome, local, media) values ('Jaskolski, Collins and Predovic', 'Brazil', 14.63);
insert into ies (nome, local, media) values ('Upton-Brown', 'Brazil', 32.07);
insert into ies (nome, local, media) values ('Moore, Greenfelder and Pfeffer', 'Brazil', 52.91);
insert into ies (nome, local, media) values ('Harber LLC', 'Brazil', 91.39);
insert into ies (nome, local, media) values ('White, Moen and Christiansen', 'Brazil', 53.01);
insert into ies (nome, local, media) values ('Schuppe, Mosciski and Schinner', 'Brazil', 14.09);
insert into ies (nome, local, media) values ('Rodriguez Group', 'Brazil', 90.29);
insert into ies (nome, local, media) values ('Rutherford-Reichert', 'Brazil', 21.01);
insert into ies (nome, local, media) values ('Koepp-Denesik', 'Brazil', 24.27);
insert into ies (nome, local, media) values ('Brekke LLC', 'Brazil', 33.53);
insert into ies (nome, local, media) values ('Weimann, Parisian and Kuhn', 'Brazil', 64.08);
insert into ies (nome, local, media) values ('Gibson Inc', 'Brazil', 38.83);
insert into ies (nome, local, media) values ('Heathcote Group', 'Brazil', 54.23);
insert into ies (nome, local, media) values ('Smith-Brown', 'Brazil', 75.97);
insert into ies (nome, local, media) values ('Corwin LLC', 'Brazil', 20.7);
insert into ies (nome, local, media) values ('Kunde, Grady and Wuckert', 'Brazil', 85.62);
insert into ies (nome, local, media) values ('Waters, Robel and Friesen', 'Brazil', 45.23);
insert into ies (nome, local, media) values ('Williamson Group', 'Brazil', 95.41);
insert into ies (nome, local, media) values ('Cormier Group', 'Brazil', 19.48);
insert into ies (nome, local, media) values ('Pfeffer, Conn and Cremin', 'Brazil', 83.71);
insert into ies (nome, local, media) values ('Block, Rutherford and Langosh', 'Brazil', 19.37);
insert into ies (nome, local, media) values ('Hartmann, Koelpin and Lindgren', 'Brazil', 85.11);
insert into ies (nome, local, media) values ('Hodkiewicz-Emard', 'Brazil', 45.96);
insert into ies (nome, local, media) values ('Cronin and Sons', 'Brazil', 69.49);
insert into ies (nome, local, media) values ('Bayer LLC', 'Brazil', 94.79);
insert into ies (nome, local, media) values ('Lang-Heller', 'Brazil', 85.48);
insert into ies (nome, local, media) values ('Ledner, Kemmer and Conroy', 'Brazil', 34.6);
insert into ies (nome, local, media) values ('Bergstrom, Lubowitz and Wunsch', 'Brazil', 24.75);
insert into ies (nome, local, media) values ('Pacocha, Hane and Hyatt', 'Brazil', 49.82);
insert into ies (nome, local, media) values ('Gerhold, Wiegand and Turcotte', 'Brazil', 92.86);
insert into ies (nome, local, media) values ('Kulas-Dach', 'Brazil', 41.8);
insert into ies (nome, local, media) values ('McKenzie-Ullrich', 'Brazil', 64.45);
insert into ies (nome, local, media) values ('Abernathy-Keeling', 'Brazil', 47.65);
insert into ies (nome, local, media) values ('Koss, McGlynn and Lesch', 'Brazil', 27.19);
insert into ies (nome, local, media) values ('Wolff Group', 'Brazil', 67.77);
insert into ies (nome, local, media) values ('Cassin, Brekke and Braun', 'Brazil', 16.32);
insert into ies (nome, local, media) values ('Dooley, Cremin and Ruecker', 'Brazil', 40.16);
insert into ies (nome, local, media) values ('Dickens, Kassulke and Ward', 'Brazil', 64.52);
insert into ies (nome, local, media) values ('Greenfelder Group', 'Brazil', 80.22);
insert into ies (nome, local, media) values ('Grady LLC', 'Brazil', 73.07);
insert into ies (nome, local, media) values ('Pagac, Gerhold and Weissnat', 'Brazil', 68.64);
insert into ies (nome, local, media) values ('McDermott-Waters', 'Brazil', 63.27);
insert into ies (nome, local, media) values ('Feil and Sons', 'Brazil', 19.55);
insert into ies (nome, local, media) values ('Hane, Schulist and Marquardt', 'Brazil', 10.29);
insert into ies (nome, local, media) values ('Smitham-Lesch', 'Brazil', 90.79);
insert into ies (nome, local, media) values ('Bednar, Murphy and Dickinson', 'Brazil', 83.76);
insert into ies (nome, local, media) values ('Jacobs, Bosco and Rice', 'Brazil', 70.54);
insert into ies (nome, local, media) values ('Wisozk, Rempel and White', 'Brazil', 70.71);
insert into ies (nome, local, media) values ('Ratke-Dooley', 'Brazil', 28.41);
insert into ies (nome, local, media) values ('McGlynn-Denesik', 'Brazil', 61.91);
insert into ies (nome, local, media) values ('Kuhic Inc', 'Brazil', 88.86);
insert into ies (nome, local, media) values ('Hilpert, Hegmann and Blick', 'Brazil', 85.28);
insert into ies (nome, local, media) values ('Marquardt, Corkery and Kris', 'Brazil', 25.91);
insert into ies (nome, local, media) values ('McCullough LLC', 'Brazil', 74.99);
insert into ies (nome, local, media) values ('Mills, Connelly and Monahan', 'Brazil', 87.32);
insert into ies (nome, local, media) values ('Rosenbaum-Carroll', 'Brazil', 92.33);
insert into ies (nome, local, media) values ('Purdy, Stoltenberg and Maggio', 'Brazil', 58.78);
insert into ies (nome, local, media) values ('Oberbrunner LLC', 'Brazil', 93.97);
insert into ies (nome, local, media) values ('Cole-Hickle', 'Brazil', 54.46);
insert into ies (nome, local, media) values ('Bartell, Romaguera and Kuphal', 'Brazil', 72.91);
insert into ies (nome, local, media) values ('Legros, Orn and Robel', 'Brazil', 29.04);
insert into ies (nome, local, media) values ('Kertzmann, Schmidt and Schoen', 'Brazil', 53.16);
insert into ies (nome, local, media) values ('Pouros, Rolfson and Wilkinson', 'Brazil', 44.97);
insert into ies (nome, local, media) values ('Gleichner, Little and Heaney', 'Brazil', 15.33);
insert into ies (nome, local, media) values ('Roob-Corwin', 'Brazil', 68.45);
insert into ies (nome, local, media) values ('Labadie Inc', 'Brazil', 61.9);
insert into ies (nome, local, media) values ('Torphy LLC', 'Brazil', 18.0);
insert into ies (nome, local, media) values ('Wintheiser LLC', 'Brazil', 66.89);
insert into ies (nome, local, media) values ('VonRueden LLC', 'Brazil', 2.81);
insert into ies (nome, local, media) values ('Luettgen, Rolfson and Gorczany', 'Brazil', 8.36);
insert into ies (nome, local, media) values ('Trantow-Green', 'Brazil', 73.7);
insert into ies (nome, local, media) values ('Dooley Inc', 'Brazil', 79.93);
insert into ies (nome, local, media) values ('Runte and Sons', 'Brazil', 70.48);
insert into ies (nome, local, media) values ('Abernathy LLC', 'Brazil', 13.32);
insert into ies (nome, local, media) values ('Wiza-Schamberger', 'Brazil', 35.72);
insert into ies (nome, local, media) values ('O''Kon and Sons', 'Brazil', 2.85);
insert into ies (nome, local, media) values ('O''Conner-Klein', 'Brazil', 83.52);
insert into ies (nome, local, media) values ('Terry Group', 'Brazil', 21.29);
insert into ies (nome, local, media) values ('Murazik Inc', 'Brazil', 68.94);
insert into ies (nome, local, media) values ('Witting-Ankunding', 'Brazil', 1.63);
insert into ies (nome, local, media) values ('Morissette Group', 'Brazil', 35.16);
insert into ies (nome, local, media) values ('Stiedemann-Corkery', 'Brazil', 7.07);
insert into ies (nome, local, media) values ('Harber-Rath', 'Brazil', 38.74);
insert into ies (nome, local, media) values ('Hessel-O''Kon', 'Brazil', 35.98);
insert into ies (nome, local, media) values ('Leannon-Waters', 'Brazil', 98.36);
insert into ies (nome, local, media) values ('Baumbach, Pagac and Tillman', 'Brazil', 64.29);
insert into ies (nome, local, media) values ('Gibson LLC', 'Brazil', 29.08);
insert into ies (nome, local, media) values ('Reinger-Wyman', 'Brazil', 2.85);
insert into ies (nome, local, media) values ('Wisoky and Sons', 'Brazil', 44.11);
insert into ies (nome, local, media) values ('Jones and Sons', 'Brazil', 17.37);
insert into ies (nome, local, media) values ('Feest-Hamill', 'Brazil', 78.53);
insert into ies (nome, local, media) values ('Harber, Feest and Cremin', 'Brazil', 19.59);
insert into ies (nome, local, media) values ('Nikolaus, Olson and Krajcik', 'Brazil', 87.39);
insert into ies (nome, local, media) values ('Lakin, Trantow and Denesik', 'Brazil', 92.08);
insert into ies (nome, local, media) values ('Powlowski-Baumbach', 'Brazil', 92.01);
insert into ies (nome, local, media) values ('Kemmer, Johns and Feil', 'Brazil', 86.45);
insert into ies (nome, local, media) values ('Lakin, Jacobi and Armstrong', 'Brazil', 87.55);
insert into ies (nome, local, media) values ('Zemlak-Bartell', 'Brazil', 77.66);
insert into ies (nome, local, media) values ('Sawayn and Sons', 'Brazil', 59.41);
insert into ies (nome, local, media) values ('Tillman, Auer and Oberbrunner', 'Brazil', 16.22);
insert into ies (nome, local, media) values ('McDermott-Morar', 'Brazil', 71.61);
insert into ies (nome, local, media) values ('Gutmann and Sons', 'Brazil', 57.17);
insert into ies (nome, local, media) values ('Heller, Bayer and Hammes', 'Brazil', 37.57);
insert into ies (nome, local, media) values ('Moen-Harvey', 'Brazil', 45.77);
insert into ies (nome, local, media) values ('Kerluke Group', 'Brazil', 6.47);
insert into ies (nome, local, media) values ('Reinger-Collier', 'Brazil', 77.1);
insert into ies (nome, local, media) values ('Pfannerstill, Bednar and Thompson', 'Brazil', 41.61);
insert into ies (nome, local, media) values ('Torphy, Vandervort and Wunsch', 'Brazil', 23.55);
insert into ies (nome, local, media) values ('Schuster, Kohler and Murphy', 'Brazil', 35.25);
insert into ies (nome, local, media) values ('Spencer, Farrell and Macejkovic', 'Brazil', 70.93);
insert into ies (nome, local, media) values ('Quigley-Roberts', 'Brazil', 1.03);
insert into ies (nome, local, media) values ('Ward LLC', 'Brazil', 63.72);
insert into ies (nome, local, media) values ('Labadie, Harvey and Gutmann', 'Brazil', 56.62);
insert into ies (nome, local, media) values ('Nolan-Bayer', 'Brazil', 92.16);
insert into ies (nome, local, media) values ('Breitenberg, Spinka and Walter', 'Brazil', 57.81);
insert into ies (nome, local, media) values ('Flatley and Sons', 'Brazil', 50.55);
insert into ies (nome, local, media) values ('Pollich and Sons', 'Brazil', 65.06);
insert into ies (nome, local, media) values ('Cartwright-Runolfsdottir', 'Brazil', 72.13);
insert into ies (nome, local, media) values ('Zulauf-Doyle', 'Brazil', 49.34);
insert into ies (nome, local, media) values ('Terry-Powlowski', 'Brazil', 98.42);
insert into ies (nome, local, media) values ('Durgan-Watsica', 'Brazil', 90.65);
insert into ies (nome, local, media) values ('Wilkinson, Waelchi and Von', 'Brazil', 4.04);
insert into ies (nome, local, media) values ('Hartmann-Bednar', 'Brazil', 9.56);
insert into ies (nome, local, media) values ('Wolff, Quigley and Bergnaum', 'Brazil', 53.7);
insert into ies (nome, local, media) values ('Ondricka-Lowe', 'Brazil', 78.98);
insert into ies (nome, local, media) values ('Nitzsche Group', 'Brazil', 55.94);
insert into ies (nome, local, media) values ('Eichmann, Sipes and Tillman', 'Brazil', 29.42);
insert into ies (nome, local, media) values ('O''Reilly, Kris and Runolfsson', 'Brazil', 41.16);
insert into ies (nome, local, media) values ('Marquardt, Torp and Lang', 'Brazil', 24.09);
insert into ies (nome, local, media) values ('Stamm-Tillman', 'Brazil', 76.21);
insert into ies (nome, local, media) values ('Schmeler Group', 'Brazil', 94.03);
insert into ies (nome, local, media) values ('Bogisich Inc', 'Brazil', 64.94);
insert into ies (nome, local, media) values ('Kihn Inc', 'Brazil', 11.6);
insert into ies (nome, local, media) values ('Jacobs, Walker and Barton', 'Brazil', 83.82);
insert into ies (nome, local, media) values ('West, Douglas and Kling', 'Brazil', 55.21);
insert into ies (nome, local, media) values ('Denesik-Volkman', 'Brazil', 43.64);
insert into ies (nome, local, media) values ('Deckow-Harvey', 'Brazil', 78.37);
insert into ies (nome, local, media) values ('Conn-Graham', 'Brazil', 8.37);
insert into ies (nome, local, media) values ('Bashirian Group', 'Brazil', 39.53);
insert into ies (nome, local, media) values ('Wehner and Sons', 'Brazil', 97.24);
insert into ies (nome, local, media) values ('Bosco, Reinger and Heaney', 'Brazil', 75.23);
insert into ies (nome, local, media) values ('Nikolaus LLC', 'Brazil', 74.69);
insert into ies (nome, local, media) values ('Reichert and Sons', 'Brazil', 56.46);
insert into ies (nome, local, media) values ('Hoeger, Hettinger and Quigley', 'Brazil', 9.07);
insert into ies (nome, local, media) values ('Hettinger, Hane and Gusikowski', 'Brazil', 59.55);
insert into ies (nome, local, media) values ('Pfannerstill Group', 'Brazil', 36.65);
insert into ies (nome, local, media) values ('Ward and Sons', 'Brazil', 55.98);
insert into ies (nome, local, media) values ('Marks and Sons', 'Brazil', 63.23);
insert into ies (nome, local, media) values ('Thiel LLC', 'Brazil', 88.23);
insert into ies (nome, local, media) values ('Kuhn and Sons', 'Brazil', 77.95);
insert into ies (nome, local, media) values ('Mayer Group', 'Brazil', 77.34);
insert into ies (nome, local, media) values ('Volkman-Shields', 'Brazil', 14.92);
insert into ies (nome, local, media) values ('Mohr and Sons', 'Brazil', 29.17);
insert into ies (nome, local, media) values ('Schiller-Wiegand', 'Brazil', 94.99);
insert into ies (nome, local, media) values ('Senger-Trantow', 'Brazil', 18.69);
insert into ies (nome, local, media) values ('Von, Rohan and Rogahn', 'Brazil', 45.87);
insert into ies (nome, local, media) values ('Schultz, Kirlin and Maggio', 'Brazil', 21.06);
insert into ies (nome, local, media) values ('Rowe Inc', 'Brazil', 55.15);
insert into ies (nome, local, media) values ('Eichmann LLC', 'Brazil', 75.64);
insert into ies (nome, local, media) values ('Bauch LLC', 'Brazil', 40.92);
insert into ies (nome, local, media) values ('McDermott, Beahan and Maggio', 'Brazil', 85.56);
insert into ies (nome, local, media) values ('Greenfelder Inc', 'Brazil', 96.73);
insert into ies (nome, local, media) values ('Wisozk-Veum', 'Brazil', 7.01);
insert into ies (nome, local, media) values ('O''Keefe, Rogahn and Trantow', 'Brazil', 7.06);
insert into ies (nome, local, media) values ('Wilkinson-Huels', 'Brazil', 20.45);
insert into ies (nome, local, media) values ('Kessler-Heaney', 'Brazil', 37.62);
insert into ies (nome, local, media) values ('Wintheiser, King and Cormier', 'Brazil', 98.77);
insert into ies (nome, local, media) values ('Schuster, Pacocha and Mosciski', 'Brazil', 32.32);
insert into ies (nome, local, media) values ('Bergstrom-Marquardt', 'Brazil', 85.13);
insert into ies (nome, local, media) values ('Koelpin, Lindgren and Halvorson', 'Brazil', 70.8);
insert into ies (nome, local, media) values ('Orn Group', 'Brazil', 53.48);
insert into ies (nome, local, media) values ('Kirlin Group', 'Brazil', 82.67);
insert into ies (nome, local, media) values ('Koss, Harvey and Bailey', 'Brazil', 76.64);
insert into ies (nome, local, media) values ('Feeney and Sons', 'Brazil', 60.24);
insert into ies (nome, local, media) values ('Corwin, Mraz and Hyatt', 'Brazil', 87.94);
insert into ies (nome, local, media) values ('Little, Bergstrom and Carroll', 'Brazil', 13.7);
insert into ies (nome, local, media) values ('Gleichner, Schmeler and Nolan', 'Brazil', 25.05);
insert into ies (nome, local, media) values ('Rohan-Marquardt', 'Brazil', 30.03);
insert into ies (nome, local, media) values ('Hoeger-Feil', 'Brazil', 58.15);
insert into ies (nome, local, media) values ('O''Connell Group', 'Brazil', 3.84);
insert into ies (nome, local, media) values ('Rempel, Muller and McClure', 'Brazil', 56.42);
insert into ies (nome, local, media) values ('Kemmer-Satterfield', 'Brazil', 23.48);
insert into ies (nome, local, media) values ('Tremblay-Smith', 'Brazil', 69.81);
insert into ies (nome, local, media) values ('Yost, Spinka and O''Kon', 'Brazil', 66.12);
insert into ies (nome, local, media) values ('Weimann, Dooley and Mayert', 'Brazil', 89.71);
insert into ies (nome, local, media) values ('Bradtke, Wehner and Rutherford', 'Brazil', 21.02);
insert into ies (nome, local, media) values ('Metz Inc', 'Brazil', 29.95);
insert into ies (nome, local, media) values ('Boyer-Armstrong', 'Brazil', 5.23);
insert into ies (nome, local, media) values ('Jones Inc', 'Brazil', 5.21);
insert into ies (nome, local, media) values ('Abshire Inc', 'Brazil', 28.13);
insert into ies (nome, local, media) values ('Hermiston-Conroy', 'Brazil', 27.54);
insert into ies (nome, local, media) values ('Collier Inc', 'Brazil', 45.39);
insert into ies (nome, local, media) values ('Ondricka, Hermiston and Rogahn', 'Brazil', 49.52);
insert into ies (nome, local, media) values ('Williamson, Welch and Zulauf', 'Brazil', 16.16);
insert into ies (nome, local, media) values ('Cormier, VonRueden and Hessel', 'Brazil', 42.43);
insert into ies (nome, local, media) values ('Turner Inc', 'Brazil', 78.5);
insert into ies (nome, local, media) values ('Heller, Crona and Grimes', 'Brazil', 78.79);
insert into ies (nome, local, media) values ('Hodkiewicz Inc', 'Brazil', 31.46);
insert into ies (nome, local, media) values ('Bradtke-Reichert', 'Brazil', 24.42);
insert into ies (nome, local, media) values ('Beatty, Macejkovic and Lemke', 'Brazil', 72.27);
insert into ies (nome, local, media) values ('Kohler, Prosacco and Johns', 'Brazil', 68.53);
insert into ies (nome, local, media) values ('Mitchell, Mraz and Hettinger', 'Brazil', 50.32);
insert into ies (nome, local, media) values ('Prohaska LLC', 'Brazil', 9.37);
insert into ies (nome, local, media) values ('Rath LLC', 'Brazil', 55.02);
insert into ies (nome, local, media) values ('Bruen-Becker', 'Brazil', 81.06);
insert into ies (nome, local, media) values ('McLaughlin Group', 'Brazil', 74.36);
insert into ies (nome, local, media) values ('Strosin, Lakin and Kub', 'Brazil', 16.43);
insert into ies (nome, local, media) values ('Kuhlman, Senger and Sawayn', 'Brazil', 56.49);
insert into ies (nome, local, media) values ('Boyle-Jones', 'Brazil', 37.21);
insert into ies (nome, local, media) values ('VonRueden and Sons', 'Brazil', 87.89);
insert into ies (nome, local, media) values ('Collier-Kuphal', 'Brazil', 75.7);
insert into ies (nome, local, media) values ('Sanford and Sons', 'Brazil', 18.43);
insert into ies (nome, local, media) values ('Medhurst, Hudson and Feeney', 'Brazil', 68.49);
insert into ies (nome, local, media) values ('Schmeler-Lind', 'Brazil', 1.14);
insert into ies (nome, local, media) values ('Braun, Davis and Shanahan', 'Brazil', 30.63);
insert into ies (nome, local, media) values ('Bradtke-Orn', 'Brazil', 95.69);
insert into ies (nome, local, media) values ('Streich and Sons', 'Brazil', 98.95);
insert into ies (nome, local, media) values ('Ward Group', 'Brazil', 55.34);
insert into ies (nome, local, media) values ('Langworth and Sons', 'Brazil', 49.46);
insert into ies (nome, local, media) values ('O''Keefe, Hodkiewicz and Howe', 'Brazil', 30.06);
insert into ies (nome, local, media) values ('Braun, Wisoky and Murray', 'Brazil', 79.37);
insert into ies (nome, local, media) values ('White-Lemke', 'Brazil', 56.36);
insert into ies (nome, local, media) values ('Rowe, Kshlerin and Klocko', 'Brazil', 40.62);
insert into ies (nome, local, media) values ('Koelpin Group', 'Brazil', 82.53);
insert into ies (nome, local, media) values ('West and Sons', 'Brazil', 61.86);
insert into ies (nome, local, media) values ('Kris LLC', 'Brazil', 44.45);
insert into ies (nome, local, media) values ('Kihn-Spinka', 'Brazil', 91.44);
insert into ies (nome, local, media) values ('Rowe Group', 'Brazil', 72.18);
insert into ies (nome, local, media) values ('Sanford-Luettgen', 'Brazil', 75.35);
insert into ies (nome, local, media) values ('Bergnaum, Green and Halvorson', 'Brazil', 29.52);
insert into ies (nome, local, media) values ('Bechtelar Inc', 'Brazil', 28.77);
insert into ies (nome, local, media) values ('Lynch and Sons', 'Brazil', 35.65);
insert into ies (nome, local, media) values ('Schaden LLC', 'Brazil', 76.15);
insert into ies (nome, local, media) values ('Dach, Homenick and Hills', 'Brazil', 67.41);
insert into ies (nome, local, media) values ('Koss LLC', 'Brazil', 51.13);
insert into ies (nome, local, media) values ('Gorczany-Koelpin', 'Brazil', 44.89);
insert into ies (nome, local, media) values ('Harris-Block', 'Brazil', 95.75);
insert into ies (nome, local, media) values ('McLaughlin Inc', 'Brazil', 14.09);
insert into ies (nome, local, media) values ('Maggio-Rolfson', 'Brazil', 13.47);
insert into ies (nome, local, media) values ('Labadie, Schmeler and Berge', 'Brazil', 92.53);
insert into ies (nome, local, media) values ('Lehner and Sons', 'Brazil', 57.93);
insert into ies (nome, local, media) values ('Green Group', 'Brazil', 29.42);
insert into ies (nome, local, media) values ('Kuhlman-Schuster', 'Brazil', 15.58);
insert into ies (nome, local, media) values ('Stanton-Rippin', 'Brazil', 7.81);
insert into ies (nome, local, media) values ('Ernser and Sons', 'Brazil', 27.55);
insert into ies (nome, local, media) values ('Streich-Beatty', 'Brazil', 60.36);
insert into ies (nome, local, media) values ('Jast, Rice and Parker', 'Brazil', 39.72);
insert into ies (nome, local, media) values ('Aufderhar, Hamill and Tillman', 'Brazil', 77.52);
insert into ies (nome, local, media) values ('O''Hara, Roberts and Klein', 'Brazil', 31.84);
insert into ies (nome, local, media) values ('Pollich-Greenfelder', 'Brazil', 72.36);
insert into ies (nome, local, media) values ('Abbott, Langworth and Casper', 'Brazil', 41.23);
insert into ies (nome, local, media) values ('Roob-Littel', 'Brazil', 15.04);
insert into ies (nome, local, media) values ('Torp, Lebsack and Frami', 'Brazil', 51.69);
insert into ies (nome, local, media) values ('Buckridge, Muller and Bergnaum', 'Brazil', 63.99);
insert into ies (nome, local, media) values ('Bernhard Group', 'Brazil', 21.46);
insert into ies (nome, local, media) values ('Tromp-Morar', 'Brazil', 25.96);
insert into ies (nome, local, media) values ('Bins LLC', 'Brazil', 18.87);
insert into ies (nome, local, media) values ('Schiller LLC', 'Brazil', 72.85);
insert into ies (nome, local, media) values ('Keebler, Rath and Paucek', 'Brazil', 87.68);
insert into ies (nome, local, media) values ('Langworth-Simonis', 'Brazil', 16.92);
insert into ies (nome, local, media) values ('Prohaska, Runte and Smith', 'Brazil', 28.82);
insert into ies (nome, local, media) values ('Marvin-Wisoky', 'Brazil', 45.65);
insert into ies (nome, local, media) values ('Hintz-Hirthe', 'Brazil', 65.01);
insert into ies (nome, local, media) values ('Gulgowski, Becker and Armstrong', 'Brazil', 8.92);
insert into ies (nome, local, media) values ('Dicki and Sons', 'Brazil', 73.07);
insert into ies (nome, local, media) values ('Harvey-Larkin', 'Brazil', 28.36);
insert into ies (nome, local, media) values ('Hilll Inc', 'Brazil', 75.28);
insert into ies (nome, local, media) values ('Kessler, Lubowitz and Hauck', 'Brazil', 50.09);
insert into ies (nome, local, media) values ('Gutkowski, Marks and Wunsch', 'Brazil', 42.03);
insert into ies (nome, local, media) values ('Lemke, Kerluke and DuBuque', 'Brazil', 30.17);
insert into ies (nome, local, media) values ('Abbott Inc', 'Brazil', 14.25);
insert into ies (nome, local, media) values ('Lockman and Sons', 'Brazil', 42.55);
insert into ies (nome, local, media) values ('McLaughlin LLC', 'Brazil', 36.33);
insert into ies (nome, local, media) values ('Swaniawski, Botsford and Anderson', 'Brazil', 63.14);
insert into ies (nome, local, media) values ('Kassulke, Rowe and Hudson', 'Brazil', 50.47);
insert into ies (nome, local, media) values ('Lowe-Luettgen', 'Brazil', 96.76);
insert into ies (nome, local, media) values ('Rohan Group', 'Brazil', 8.93);
insert into ies (nome, local, media) values ('Weimann, Rodriguez and Luettgen', 'Brazil', 72.36);
insert into ies (nome, local, media) values ('Russel Inc', 'Brazil', 40.97);
insert into ies (nome, local, media) values ('Leuschke-Collier', 'Brazil', 73.34);
insert into ies (nome, local, media) values ('Dicki LLC', 'Brazil', 42.84);
insert into ies (nome, local, media) values ('Aufderhar, Davis and Nolan', 'Brazil', 6.08);
insert into ies (nome, local, media) values ('Kunde-McClure', 'Brazil', 16.02);
insert into ies (nome, local, media) values ('Hammes-Veum', 'Brazil', 40.46);
insert into ies (nome, local, media) values ('Effertz LLC', 'Brazil', 95.97);
insert into ies (nome, local, media) values ('Williamson, Larkin and Predovic', 'Brazil', 52.73);
insert into ies (nome, local, media) values ('Jones-D''Amore', 'Brazil', 12.9);
insert into ies (nome, local, media) values ('Bernhard Group', 'Brazil', 43.3);
insert into ies (nome, local, media) values ('Fay, Stroman and Koepp', 'Brazil', 37.8);
insert into ies (nome, local, media) values ('Spinka Inc', 'Brazil', 30.17);
insert into ies (nome, local, media) values ('Rodriguez, Mante and Herzog', 'Brazil', 84.98);
insert into ies (nome, local, media) values ('Mayer, Corkery and Schulist', 'Brazil', 87.68);
insert into ies (nome, local, media) values ('Harvey-Schulist', 'Brazil', 82.06);
insert into ies (nome, local, media) values ('Ortiz Group', 'Brazil', 41.2);
insert into ies (nome, local, media) values ('Sauer-Greenholt', 'Brazil', 75.15);
insert into ies (nome, local, media) values ('Nienow and Sons', 'Brazil', 77.73);
insert into ies (nome, local, media) values ('Adams, Wilkinson and Nitzsche', 'Brazil', 35.56);
insert into ies (nome, local, media) values ('Little, Cole and Conn', 'Brazil', 53.73);
insert into ies (nome, local, media) values ('Rau Group', 'Brazil', 42.68);
insert into ies (nome, local, media) values ('Marvin-Mitchell', 'Brazil', 61.55);
insert into ies (nome, local, media) values ('Herman Group', 'Brazil', 59.59);
insert into ies (nome, local, media) values ('Schmidt, Harris and D''Amore', 'Brazil', 92.38);
insert into ies (nome, local, media) values ('Streich, Beer and Rosenbaum', 'Brazil', 71.96);
insert into ies (nome, local, media) values ('Gerlach Inc', 'Brazil', 59.19);
insert into ies (nome, local, media) values ('Beer Inc', 'Brazil', 11.06);
insert into ies (nome, local, media) values ('Wisoky Inc', 'Brazil', 12.76);
insert into ies (nome, local, media) values ('Connelly LLC', 'Brazil', 94.26);
insert into ies (nome, local, media) values ('Cassin-Koelpin', 'Brazil', 26.98);
insert into ies (nome, local, media) values ('Bogan-Bayer', 'Brazil', 3.55);
insert into ies (nome, local, media) values ('Rath, Barrows and Hintz', 'Brazil', 32.09);
insert into ies (nome, local, media) values ('O''Conner, Rath and Hane', 'Brazil', 60.85);
insert into ies (nome, local, media) values ('Hamill LLC', 'Brazil', 62.47);
insert into ies (nome, local, media) values ('Rippin, Auer and Stroman', 'Brazil', 66.13);
insert into ies (nome, local, media) values ('Bednar and Sons', 'Brazil', 50.21);
insert into ies (nome, local, media) values ('Schuppe-Howell', 'Brazil', 32.86);
insert into ies (nome, local, media) values ('Batz-Thiel', 'Brazil', 46.9);
insert into ies (nome, local, media) values ('Johnston Group', 'Brazil', 8.54);
insert into ies (nome, local, media) values ('Walter, Mann and Lubowitz', 'Brazil', 98.63);
insert into ies (nome, local, media) values ('Schinner, Turner and Koepp', 'Brazil', 34.2);
insert into ies (nome, local, media) values ('Homenick-O''Conner', 'Brazil', 14.56);
insert into ies (nome, local, media) values ('Grimes-Blanda', 'Brazil', 45.65);
insert into ies (nome, local, media) values ('Bailey, Hansen and Boyer', 'Brazil', 6.15);
insert into ies (nome, local, media) values ('Abernathy-Stracke', 'Brazil', 1.28);
insert into ies (nome, local, media) values ('Funk Group', 'Brazil', 86.65);
insert into ies (nome, local, media) values ('Champlin and Sons', 'Brazil', 39.21);
insert into ies (nome, local, media) values ('Cronin Inc', 'Brazil', 11.59);
insert into ies (nome, local, media) values ('Wilderman Inc', 'Brazil', 31.69);
insert into ies (nome, local, media) values ('Rosenbaum Group', 'Brazil', 19.08);
insert into ies (nome, local, media) values ('Pfeffer-Becker', 'Brazil', 98.12);
insert into ies (nome, local, media) values ('Mueller-Ward', 'Brazil', 9.15);
insert into ies (nome, local, media) values ('Hauck-Leuschke', 'Brazil', 85.5);
insert into ies (nome, local, media) values ('Corwin Inc', 'Brazil', 12.33);
insert into ies (nome, local, media) values ('D''Amore, Rice and Harris', 'Brazil', 22.83);
insert into ies (nome, local, media) values ('Abshire, Sawayn and Hoppe', 'Brazil', 15.88);
insert into ies (nome, local, media) values ('Bradtke and Sons', 'Brazil', 57.88);
insert into ies (nome, local, media) values ('Borer-Heaney', 'Brazil', 74.29);
insert into ies (nome, local, media) values ('Bahringer-Stehr', 'Brazil', 9.68);
insert into ies (nome, local, media) values ('Bergstrom and Sons', 'Brazil', 74.25);
insert into ies (nome, local, media) values ('Jenkins-Ernser', 'Brazil', 87.52);
insert into ies (nome, local, media) values ('Berge-Wuckert', 'Brazil', 22.94);
insert into ies (nome, local, media) values ('Prohaska Inc', 'Brazil', 58.11);
insert into ies (nome, local, media) values ('Farrell-Corwin', 'Brazil', 51.43);
insert into ies (nome, local, media) values ('Monahan LLC', 'Brazil', 7.43);
insert into ies (nome, local, media) values ('Altenwerth and Sons', 'Brazil', 16.01);
insert into ies (nome, local, media) values ('Roob-Halvorson', 'Brazil', 32.84);
insert into ies (nome, local, media) values ('Murphy-Harris', 'Brazil', 84.49);
insert into ies (nome, local, media) values ('Gleichner-Dare', 'Brazil', 17.65);
insert into ies (nome, local, media) values ('Hegmann LLC', 'Brazil', 39.64);
insert into ies (nome, local, media) values ('Mertz and Sons', 'Brazil', 51.46);
insert into ies (nome, local, media) values ('Reilly Group', 'Brazil', 43.54);
insert into ies (nome, local, media) values ('McGlynn Group', 'Brazil', 14.32);
insert into ies (nome, local, media) values ('Simonis, Ebert and Glover', 'Brazil', 58.89);
insert into ies (nome, local, media) values ('Sipes and Sons', 'Brazil', 25.67);
insert into ies (nome, local, media) values ('O''Kon, Rau and Mills', 'Brazil', 81.96);
insert into ies (nome, local, media) values ('Mayert Group', 'Brazil', 39.13);
insert into ies (nome, local, media) values ('Cummerata, Koepp and Ledner', 'Brazil', 13.27);
insert into ies (nome, local, media) values ('Moore-Dickens', 'Brazil', 5.03);
insert into ies (nome, local, media) values ('Fritsch-Swift', 'Brazil', 79.94);
insert into ies (nome, local, media) values ('Ferry and Sons', 'Brazil', 71.41);
insert into ies (nome, local, media) values ('Legros-Dibbert', 'Brazil', 40.96);
insert into ies (nome, local, media) values ('Stehr, Paucek and Leffler', 'Brazil', 85.65);
insert into ies (nome, local, media) values ('Harber Group', 'Brazil', 65.01);
insert into ies (nome, local, media) values ('Jones Inc', 'Brazil', 85.53);
insert into ies (nome, local, media) values ('Ferry-Russel', 'Brazil', 33.91);
insert into ies (nome, local, media) values ('Pacocha, Leannon and Koelpin', 'Brazil', 55.35);
insert into ies (nome, local, media) values ('Rogahn-Lind', 'Brazil', 80.69);
insert into ies (nome, local, media) values ('Dietrich-McCullough', 'Brazil', 92.48);
insert into ies (nome, local, media) values ('Koch Inc', 'Brazil', 68.43);
insert into ies (nome, local, media) values ('Spencer Group', 'Brazil', 70.8);
insert into ies (nome, local, media) values ('Koch-Nikolaus', 'Brazil', 11.04);
insert into ies (nome, local, media) values ('Nader, Johnston and Ziemann', 'Brazil', 89.37);
insert into ies (nome, local, media) values ('Predovic-Morissette', 'Brazil', 92.4);
insert into ies (nome, local, media) values ('Jenkins, Parker and Connelly', 'Brazil', 39.27);
insert into ies (nome, local, media) values ('Orn Group', 'Brazil', 69.83);
insert into ies (nome, local, media) values ('Metz, Fahey and Hodkiewicz', 'Brazil', 93.98);
insert into ies (nome, local, media) values ('Ernser, O''Conner and Gerlach', 'Brazil', 15.97);
insert into ies (nome, local, media) values ('Gulgowski-Padberg', 'Brazil', 15.33);
insert into ies (nome, local, media) values ('Ondricka-Bashirian', 'Brazil', 48.12);
insert into ies (nome, local, media) values ('Flatley, Funk and Anderson', 'Brazil', 29.65);
insert into ies (nome, local, media) values ('Medhurst-McLaughlin', 'Brazil', 56.67);
insert into ies (nome, local, media) values ('Hickle, Brekke and Rath', 'Brazil', 93.77);
insert into ies (nome, local, media) values ('Bergstrom, Funk and Windler', 'Brazil', 47.24);
insert into ies (nome, local, media) values ('Ledner-Christiansen', 'Brazil', 53.13);
insert into ies (nome, local, media) values ('Ankunding Group', 'Brazil', 1.28);
insert into ies (nome, local, media) values ('Bernhard, Witting and White', 'Brazil', 34.85);
insert into ies (nome, local, media) values ('Osinski Group', 'Brazil', 6.82);
insert into ies (nome, local, media) values ('Klocko Group', 'Brazil', 99.31);
insert into ies (nome, local, media) values ('Mueller, Lubowitz and Schaden', 'Brazil', 15.44);
insert into ies (nome, local, media) values ('Kuhlman, Goldner and Sporer', 'Brazil', 50.7);
insert into ies (nome, local, media) values ('Schoen, Cassin and O''Kon', 'Brazil', 56.82);
insert into ies (nome, local, media) values ('Connelly Inc', 'Brazil', 42.69);
insert into ies (nome, local, media) values ('Ondricka-Will', 'Brazil', 45.81);
insert into ies (nome, local, media) values ('Hagenes Group', 'Brazil', 60.5);
insert into ies (nome, local, media) values ('McClure and Sons', 'Brazil', 27.06);
insert into ies (nome, local, media) values ('Hermann LLC', 'Brazil', 53.02);
insert into ies (nome, local, media) values ('Mosciski and Sons', 'Brazil', 15.48);
insert into ies (nome, local, media) values ('Schamberger, Cole and Cummings', 'Brazil', 83.73);
insert into ies (nome, local, media) values ('Cremin LLC', 'Brazil', 97.8);
insert into ies (nome, local, media) values ('Douglas-Huels', 'Brazil', 78.87);
insert into ies (nome, local, media) values ('Treutel LLC', 'Brazil', 17.07);
insert into ies (nome, local, media) values ('Kihn, Kassulke and Pollich', 'Brazil', 4.06);
insert into ies (nome, local, media) values ('Feil Inc', 'Brazil', 77.78);
insert into ies (nome, local, media) values ('Ortiz-Becker', 'Brazil', 84.94);
insert into ies (nome, local, media) values ('Vandervort, Ebert and Gibson', 'Brazil', 60.41);
insert into ies (nome, local, media) values ('McCullough, Quigley and Bailey', 'Brazil', 17.63);
insert into ies (nome, local, media) values ('Raynor LLC', 'Brazil', 31.48);
insert into ies (nome, local, media) values ('Abshire and Sons', 'Brazil', 31.29);
insert into ies (nome, local, media) values ('Reynolds-Cronin', 'Brazil', 58.06);
insert into ies (nome, local, media) values ('Stracke-Stokes', 'Brazil', 26.74);
insert into ies (nome, local, media) values ('Gottlieb LLC', 'Brazil', 46.38);
insert into ies (nome, local, media) values ('Ziemann, Terry and Pfannerstill', 'Brazil', 40.24);
insert into ies (nome, local, media) values ('Keebler LLC', 'Brazil', 52.33);
insert into ies (nome, local, media) values ('Boyer Group', 'Brazil', 11.54);
insert into ies (nome, local, media) values ('Gleichner-Hintz', 'Brazil', 85.84);
insert into ies (nome, local, media) values ('Carroll, Tromp and Monahan', 'Brazil', 22.56);
insert into ies (nome, local, media) values ('Rutherford-Hahn', 'Brazil', 88.5);
insert into ies (nome, local, media) values ('Zemlak Group', 'Brazil', 9.0);
insert into ies (nome, local, media) values ('Mohr and Sons', 'Brazil', 94.83);
insert into ies (nome, local, media) values ('Crona-Russel', 'Brazil', 92.02);
insert into ies (nome, local, media) values ('Krajcik, Deckow and Schoen', 'Brazil', 86.88);
insert into ies (nome, local, media) values ('Weber, West and Veum', 'Brazil', 23.59);
insert into ies (nome, local, media) values ('Senger Group', 'Brazil', 45.33);
insert into ies (nome, local, media) values ('Gleason, Brekke and Gusikowski', 'Brazil', 51.27);
insert into ies (nome, local, media) values ('Barton LLC', 'Brazil', 2.56);
insert into ies (nome, local, media) values ('Hartmann, Hilll and Hammes', 'Brazil', 24.91);
insert into ies (nome, local, media) values ('Jerde-Baumbach', 'Brazil', 92.98);
insert into ies (nome, local, media) values ('Weber LLC', 'Brazil', 41.54);
insert into ies (nome, local, media) values ('Rodriguez Group', 'Brazil', 81.25);
insert into ies (nome, local, media) values ('Gutmann Group', 'Brazil', 88.59);
insert into ies (nome, local, media) values ('Bartell-Thiel', 'Brazil', 30.44);
insert into ies (nome, local, media) values ('Kulas, Veum and Larkin', 'Brazil', 50.91);
insert into ies (nome, local, media) values ('Funk Inc', 'Brazil', 83.9);
insert into ies (nome, local, media) values ('Powlowski-Frami', 'Brazil', 9.2);
insert into ies (nome, local, media) values ('White-Shanahan', 'Brazil', 61.73);
insert into ies (nome, local, media) values ('Cassin, Pacocha and Bernhard', 'Brazil', 86.0);
insert into ies (nome, local, media) values ('Mueller-Sporer', 'Brazil', 72.03);
insert into ies (nome, local, media) values ('Mertz Group', 'Brazil', 55.23);
insert into ies (nome, local, media) values ('Ward LLC', 'Brazil', 12.51);
insert into ies (nome, local, media) values ('Yost LLC', 'Brazil', 58.91);
insert into ies (nome, local, media) values ('Torp and Sons', 'Brazil', 19.84);
insert into ies (nome, local, media) values ('Kuhlman, Grady and Friesen', 'Brazil', 69.28);
insert into ies (nome, local, media) values ('Gleichner, Abshire and Kuphal', 'Brazil', 2.42);
insert into ies (nome, local, media) values ('Koss and Sons', 'Brazil', 46.93);
insert into ies (nome, local, media) values ('Ankunding-Casper', 'Brazil', 22.18);
insert into ies (nome, local, media) values ('Breitenberg-Schroeder', 'Brazil', 79.37);
insert into ies (nome, local, media) values ('Auer, Mayert and Kuhlman', 'Brazil', 94.24);
insert into ies (nome, local, media) values ('Bailey, Ziemann and Bogisich', 'Brazil', 50.59);
insert into ies (nome, local, media) values ('Ankunding LLC', 'Brazil', 89.62);
insert into ies (nome, local, media) values ('Goyette, Stehr and Crooks', 'Brazil', 73.55);
insert into ies (nome, local, media) values ('O''Kon-Schowalter', 'Brazil', 74.58);
insert into ies (nome, local, media) values ('Schiller, Dooley and Kris', 'Brazil', 70.36);
insert into ies (nome, local, media) values ('Baumbach-Ullrich', 'Brazil', 25.44);
insert into ies (nome, local, media) values ('Jacobs, Hilpert and Frami', 'Brazil', 59.61);
insert into ies (nome, local, media) values ('Schuster-Feil', 'Brazil', 84.68);
insert into ies (nome, local, media) values ('Walter Inc', 'Brazil', 64.94);
insert into ies (nome, local, media) values ('Casper and Sons', 'Brazil', 23.86);
insert into ies (nome, local, media) values ('Maggio, Ferry and Reilly', 'Brazil', 46.56);
insert into ies (nome, local, media) values ('Nienow LLC', 'Brazil', 10.29);
insert into ies (nome, local, media) values ('Gleichner Inc', 'Brazil', 62.1);
insert into ies (nome, local, media) values ('Emard, Crooks and Fritsch', 'Brazil', 28.03);
insert into ies (nome, local, media) values ('Maggio, Gislason and Parker', 'Brazil', 86.86);
insert into ies (nome, local, media) values ('Schinner-Jast', 'Brazil', 56.74);
insert into ies (nome, local, media) values ('Spinka-Osinski', 'Brazil', 23.45);
insert into ies (nome, local, media) values ('Thiel LLC', 'Brazil', 42.32);
insert into ies (nome, local, media) values ('Wintheiser and Sons', 'Brazil', 56.9);
insert into ies (nome, local, media) values ('Bailey Inc', 'Brazil', 84.3);
insert into ies (nome, local, media) values ('Morissette-Schaden', 'Brazil', 4.87);
insert into ies (nome, local, media) values ('Jaskolski LLC', 'Brazil', 67.89);
insert into ies (nome, local, media) values ('King Inc', 'Brazil', 40.02);
insert into ies (nome, local, media) values ('Koch, Turner and Feeney', 'Brazil', 63.58);
insert into ies (nome, local, media) values ('Schinner-O''Connell', 'Brazil', 15.73);
insert into ies (nome, local, media) values ('Johnson-Douglas', 'Brazil', 8.68);
insert into ies (nome, local, media) values ('Koch, Crona and Reilly', 'Brazil', 95.57);
insert into ies (nome, local, media) values ('Kihn, Kutch and Yost', 'Brazil', 75.13);
insert into ies (nome, local, media) values ('Wisozk-McClure', 'Brazil', 93.23);
insert into ies (nome, local, media) values ('Howell, Pacocha and McGlynn', 'Brazil', 11.69);
insert into ies (nome, local, media) values ('Bogan-Toy', 'Brazil', 5.93);
insert into ies (nome, local, media) values ('Mohr-Stokes', 'Brazil', 48.96);
insert into ies (nome, local, media) values ('Davis Inc', 'Brazil', 15.52);
insert into ies (nome, local, media) values ('Greenholt, Bogan and Bernier', 'Brazil', 97.88);
insert into ies (nome, local, media) values ('Lindgren, Smith and Krajcik', 'Brazil', 32.65);
insert into ies (nome, local, media) values ('McCullough, Langworth and Green', 'Brazil', 47.94);
insert into ies (nome, local, media) values ('Bradtke Inc', 'Brazil', 20.14);
insert into ies (nome, local, media) values ('Kerluke-Dooley', 'Brazil', 83.2);
insert into ies (nome, local, media) values ('Bartell, Rogahn and Collier', 'Brazil', 78.13);
insert into ies (nome, local, media) values ('Heaney-Pfeffer', 'Brazil', 43.0);
insert into ies (nome, local, media) values ('Schmeler-Beer', 'Brazil', 11.57);
insert into ies (nome, local, media) values ('Mayer Group', 'Brazil', 2.8);
insert into ies (nome, local, media) values ('McGlynn, Ebert and Roob', 'Brazil', 97.03);
insert into ies (nome, local, media) values ('Schinner, Jones and Jast', 'Brazil', 45.08);
insert into ies (nome, local, media) values ('Gaylord Inc', 'Brazil', 11.71);
insert into ies (nome, local, media) values ('Hudson, Tremblay and Brekke', 'Brazil', 50.73);
insert into ies (nome, local, media) values ('Kuhic-Funk', 'Brazil', 18.96);
insert into ies (nome, local, media) values ('Murazik-Lebsack', 'Brazil', 41.0);
insert into ies (nome, local, media) values ('Monahan and Sons', 'Brazil', 84.87);
insert into ies (nome, local, media) values ('Mitchell-Schulist', 'Brazil', 69.02);
insert into ies (nome, local, media) values ('Harris-Streich', 'Brazil', 79.9);
insert into ies (nome, local, media) values ('Rath-Blick', 'Brazil', 66.57);
insert into ies (nome, local, media) values ('Littel LLC', 'Brazil', 48.14);
insert into ies (nome, local, media) values ('Stamm Group', 'Brazil', 62.36);
insert into ies (nome, local, media) values ('Konopelski and Sons', 'Brazil', 66.76);
insert into ies (nome, local, media) values ('Moen, Osinski and Stracke', 'Brazil', 85.81);
insert into ies (nome, local, media) values ('Lynch-O''Reilly', 'Brazil', 48.59);
insert into ies (nome, local, media) values ('Upton, Conn and Stroman', 'Brazil', 15.65);
insert into ies (nome, local, media) values ('Walker-Fay', 'Brazil', 78.04);
insert into ies (nome, local, media) values ('Glover LLC', 'Brazil', 62.63);
insert into ies (nome, local, media) values ('Satterfield LLC', 'Brazil', 30.02);
insert into ies (nome, local, media) values ('O''Connell, Schuster and Gorczany', 'Brazil', 77.63);
insert into ies (nome, local, media) values ('Reichert and Sons', 'Brazil', 27.52);
insert into ies (nome, local, media) values ('Moore, Doyle and Pagac', 'Brazil', 37.29);
insert into ies (nome, local, media) values ('Gerlach and Sons', 'Brazil', 2.1);
insert into ies (nome, local, media) values ('West Inc', 'Brazil', 53.68);
insert into ies (nome, local, media) values ('Kshlerin and Sons', 'Brazil', 64.94);
insert into ies (nome, local, media) values ('Bode-Gutkowski', 'Brazil', 40.28);
insert into ies (nome, local, media) values ('Hoppe, Wolf and Huel', 'Brazil', 93.68);
insert into ies (nome, local, media) values ('Osinski-Hudson', 'Brazil', 31.2);
insert into ies (nome, local, media) values ('Wintheiser, Schaefer and Kub', 'Brazil', 20.31);
insert into ies (nome, local, media) values ('Abernathy, Kautzer and Mohr', 'Brazil', 95.86);
insert into ies (nome, local, media) values ('Lockman Group', 'Brazil', 90.32);
insert into ies (nome, local, media) values ('Stoltenberg and Sons', 'Brazil', 74.35);
insert into ies (nome, local, media) values ('Rutherford, Brekke and Daugherty', 'Brazil', 51.18);
insert into ies (nome, local, media) values ('Legros, Reilly and Kunze', 'Brazil', 53.72);
insert into ies (nome, local, media) values ('Satterfield Group', 'Brazil', 83.93);
insert into ies (nome, local, media) values ('Sauer, Heaney and Huels', 'Brazil', 59.58);
insert into ies (nome, local, media) values ('Raynor LLC', 'Brazil', 27.27);
insert into ies (nome, local, media) values ('Mraz, Bechtelar and Zulauf', 'Brazil', 98.11);
insert into ies (nome, local, media) values ('Lubowitz LLC', 'Brazil', 51.22);
insert into ies (nome, local, media) values ('Dooley LLC', 'Brazil', 43.75);
insert into ies (nome, local, media) values ('Schulist-Halvorson', 'Brazil', 65.99);
insert into ies (nome, local, media) values ('Larson, Zieme and Will', 'Brazil', 27.63);
insert into ies (nome, local, media) values ('Waters, Lehner and Hodkiewicz', 'Brazil', 52.48);
insert into ies (nome, local, media) values ('Morissette-Williamson', 'Brazil', 12.56);
insert into ies (nome, local, media) values ('Blanda-Ferry', 'Brazil', 82.62);
insert into ies (nome, local, media) values ('Gleason, Donnelly and Sipes', 'Brazil', 40.18);
insert into ies (nome, local, media) values ('Kautzer-Kub', 'Brazil', 4.05);
insert into ies (nome, local, media) values ('Auer-Doyle', 'Brazil', 59.71);
insert into ies (nome, local, media) values ('Lakin-Goldner', 'Brazil', 52.01);
insert into ies (nome, local, media) values ('Auer-Crooks', 'Brazil', 48.07);
insert into ies (nome, local, media) values ('Rippin Group', 'Brazil', 73.9);
insert into ies (nome, local, media) values ('Batz Inc', 'Brazil', 61.41);
insert into ies (nome, local, media) values ('Watsica, Effertz and Reilly', 'Brazil', 36.72);
insert into ies (nome, local, media) values ('Jacobs-Hansen', 'Brazil', 6.39);
insert into ies (nome, local, media) values ('Stehr LLC', 'Brazil', 37.33);
insert into ies (nome, local, media) values ('Moen-Boyer', 'Brazil', 89.94);
insert into ies (nome, local, media) values ('Heidenreich, Dach and Beahan', 'Brazil', 7.06);
insert into ies (nome, local, media) values ('O''Connell, Swift and Beer', 'Brazil', 64.83);
insert into ies (nome, local, media) values ('Kemmer, Halvorson and Flatley', 'Brazil', 14.29);
insert into ies (nome, local, media) values ('Johns, Farrell and Stehr', 'Brazil', 7.83);
insert into ies (nome, local, media) values ('Bashirian-Wolf', 'Brazil', 89.65);
insert into ies (nome, local, media) values ('Mayert-Koch', 'Brazil', 47.21);
insert into ies (nome, local, media) values ('Grimes, Rau and O''Connell', 'Brazil', 90.97);
insert into ies (nome, local, media) values ('Barrows and Sons', 'Brazil', 53.96);
insert into ies (nome, local, media) values ('Gerhold-Shields', 'Brazil', 43.71);
insert into ies (nome, local, media) values ('Bernhard Group', 'Brazil', 98.23);
insert into ies (nome, local, media) values ('Klein, Rath and Christiansen', 'Brazil', 56.55);
insert into ies (nome, local, media) values ('Reynolds, Torp and Durgan', 'Brazil', 32.09);
insert into ies (nome, local, media) values ('Macejkovic-Daniel', 'Brazil', 85.96);
insert into ies (nome, local, media) values ('Ritchie Group', 'Brazil', 50.74);
insert into ies (nome, local, media) values ('Gulgowski-Gottlieb', 'Brazil', 69.78);
insert into ies (nome, local, media) values ('McCullough Group', 'Brazil', 63.59);
insert into ies (nome, local, media) values ('Pagac Group', 'Brazil', 40.02);
insert into ies (nome, local, media) values ('Klein, Carroll and McClure', 'Brazil', 96.36);
insert into ies (nome, local, media) values ('Russel Group', 'Brazil', 23.34);
insert into ies (nome, local, media) values ('Nolan-Towne', 'Brazil', 87.63);
insert into ies (nome, local, media) values ('Breitenberg LLC', 'Brazil', 42.0);
insert into ies (nome, local, media) values ('Fay-Gutkowski', 'Brazil', 57.09);
insert into ies (nome, local, media) values ('Berge-Purdy', 'Brazil', 78.09);
insert into ies (nome, local, media) values ('Stroman and Sons', 'Brazil', 47.72);
insert into ies (nome, local, media) values ('Wuckert Group', 'Brazil', 36.26);
insert into ies (nome, local, media) values ('Schowalter Inc', 'Brazil', 56.05);
insert into ies (nome, local, media) values ('Ryan LLC', 'Brazil', 52.08);
insert into ies (nome, local, media) values ('Kuhic-Orn', 'Brazil', 69.68);
insert into ies (nome, local, media) values ('Klein and Sons', 'Brazil', 70.35);
insert into ies (nome, local, media) values ('Crooks and Sons', 'Brazil', 74.37);
insert into ies (nome, local, media) values ('Glover, Beer and Osinski', 'Brazil', 74.44);
insert into ies (nome, local, media) values ('Macejkovic-Simonis', 'Brazil', 11.27);
insert into ies (nome, local, media) values ('Buckridge-Schinner', 'Brazil', 4.83);
insert into ies (nome, local, media) values ('Streich LLC', 'Brazil', 59.46);
insert into ies (nome, local, media) values ('Donnelly, Hartmann and Effertz', 'Brazil', 65.79);
insert into ies (nome, local, media) values ('Rau LLC', 'Brazil', 93.98);
insert into ies (nome, local, media) values ('Armstrong, Leuschke and Daugherty', 'Brazil', 85.8);
insert into ies (nome, local, media) values ('Hane-Schuster', 'Brazil', 34.28);
insert into ies (nome, local, media) values ('Treutel LLC', 'Brazil', 48.27);
insert into ies (nome, local, media) values ('Simonis Inc', 'Brazil', 77.58);
insert into ies (nome, local, media) values ('Dickinson, Graham and Brown', 'Brazil', 69.44);
insert into ies (nome, local, media) values ('Walter Group', 'Brazil', 17.54);
insert into ies (nome, local, media) values ('Lang and Sons', 'Brazil', 66.66);
insert into ies (nome, local, media) values ('Stanton LLC', 'Brazil', 54.78);
insert into ies (nome, local, media) values ('Auer-Legros', 'Brazil', 85.94);
insert into ies (nome, local, media) values ('White, Hirthe and Schumm', 'Brazil', 34.11);
insert into ies (nome, local, media) values ('Glover, Smitham and Kihn', 'Brazil', 55.99);
insert into ies (nome, local, media) values ('Grimes, Cassin and Waters', 'Brazil', 84.36);
insert into ies (nome, local, media) values ('Goyette-Rodriguez', 'Brazil', 99.35);
insert into ies (nome, local, media) values ('Homenick-Miller', 'Brazil', 74.52);
insert into ies (nome, local, media) values ('Swift-Hegmann', 'Brazil', 21.4);
insert into ies (nome, local, media) values ('Emmerich-Ortiz', 'Brazil', 25.29);
insert into ies (nome, local, media) values ('Wiza LLC', 'Brazil', 82.52);
insert into ies (nome, local, media) values ('Miller, Cremin and Boehm', 'Brazil', 11.55);
insert into ies (nome, local, media) values ('Gislason and Sons', 'Brazil', 87.29);
insert into ies (nome, local, media) values ('Moen-Dooley', 'Brazil', 63.76);
insert into ies (nome, local, media) values ('Kerluke, Carroll and Mraz', 'Brazil', 6.25);
insert into ies (nome, local, media) values ('Rolfson Group', 'Brazil', 76.47);
insert into ies (nome, local, media) values ('Aufderhar, Schowalter and Emmerich', 'Brazil', 19.28);
insert into ies (nome, local, media) values ('Hoeger, Casper and Stehr', 'Brazil', 63.31);
insert into ies (nome, local, media) values ('Howe-Nitzsche', 'Brazil', 43.53);
insert into ies (nome, local, media) values ('Moore and Sons', 'Brazil', 15.81);
insert into ies (nome, local, media) values ('Effertz LLC', 'Brazil', 56.19);
insert into ies (nome, local, media) values ('Hilll-Mante', 'Brazil', 80.04);
insert into ies (nome, local, media) values ('Hettinger, Hoppe and Morar', 'Brazil', 99.73);
insert into ies (nome, local, media) values ('Gulgowski-Hartmann', 'Brazil', 4.89);
insert into ies (nome, local, media) values ('Leuschke-Ward', 'Brazil', 84.59);
insert into ies (nome, local, media) values ('Crist LLC', 'Brazil', 89.84);
insert into ies (nome, local, media) values ('Herzog-Luettgen', 'Brazil', 16.84);
insert into ies (nome, local, media) values ('Dooley, Braun and Kreiger', 'Brazil', 89.91);
insert into ies (nome, local, media) values ('Rath Group', 'Brazil', 49.14);
insert into ies (nome, local, media) values ('Dickens, Walsh and Shanahan', 'Brazil', 44.18);
insert into ies (nome, local, media) values ('McLaughlin, Ritchie and Tillman', 'Brazil', 97.25);
insert into ies (nome, local, media) values ('Brakus, Bins and Pacocha', 'Brazil', 8.52);
insert into ies (nome, local, media) values ('Beier, Orn and Franecki', 'Brazil', 80.05);
insert into ies (nome, local, media) values ('VonRueden-Bartell', 'Brazil', 44.84);
insert into ies (nome, local, media) values ('Hoeger, Schmeler and Weimann', 'Brazil', 4.61);
insert into ies (nome, local, media) values ('McLaughlin LLC', 'Brazil', 34.1);
insert into ies (nome, local, media) values ('Rutherford, Thiel and Abshire', 'Brazil', 64.72);
insert into ies (nome, local, media) values ('Jenkins, Littel and Reynolds', 'Brazil', 86.6);
insert into ies (nome, local, media) values ('Bauch Group', 'Brazil', 16.97);
insert into ies (nome, local, media) values ('Welch Inc', 'Brazil', 77.61);
insert into ies (nome, local, media) values ('Fritsch Inc', 'Brazil', 47.56);
insert into ies (nome, local, media) values ('Cummings and Sons', 'Brazil', 73.99);
insert into ies (nome, local, media) values ('Gleichner, Block and Mayert', 'Brazil', 82.6);
insert into ies (nome, local, media) values ('Torp, Cruickshank and Ryan', 'Brazil', 23.2);
insert into ies (nome, local, media) values ('Bruen, Lynch and Stokes', 'Brazil', 47.81);
insert into ies (nome, local, media) values ('Rohan, Zulauf and Watsica', 'Brazil', 84.58);
insert into ies (nome, local, media) values ('Corwin Inc', 'Brazil', 25.08);
insert into ies (nome, local, media) values ('Lemke, Schumm and McKenzie', 'Brazil', 54.34);
insert into ies (nome, local, media) values ('Legros Inc', 'Brazil', 91.72);
insert into ies (nome, local, media) values ('Rosenbaum and Sons', 'Brazil', 11.4);
insert into ies (nome, local, media) values ('Bernhard-Harris', 'Brazil', 16.91);
insert into ies (nome, local, media) values ('Stehr Inc', 'Brazil', 31.79);
insert into ies (nome, local, media) values ('Mann, Skiles and Koelpin', 'Brazil', 50.31);
insert into ies (nome, local, media) values ('Farrell, Jerde and Treutel', 'Brazil', 81.93);
insert into ies (nome, local, media) values ('Bode and Sons', 'Brazil', 93.43);
insert into ies (nome, local, media) values ('Bartoletti Inc', 'Brazil', 16.7);
insert into ies (nome, local, media) values ('Ward-McGlynn', 'Brazil', 68.15);
insert into ies (nome, local, media) values ('Ledner, Boehm and Schulist', 'Brazil', 86.34);
insert into ies (nome, local, media) values ('Bartell Group', 'Brazil', 34.36);
insert into ies (nome, local, media) values ('Christiansen, Frami and Roob', 'Brazil', 96.56);
insert into ies (nome, local, media) values ('Thiel, Larson and Schroeder', 'Brazil', 45.98);
insert into ies (nome, local, media) values ('Gutmann Inc', 'Brazil', 70.11);
insert into ies (nome, local, media) values ('Emmerich LLC', 'Brazil', 94.31);
insert into ies (nome, local, media) values ('Goldner, Lebsack and Howe', 'Brazil', 77.71);
insert into ies (nome, local, media) values ('Nitzsche-Casper', 'Brazil', 88.79);
insert into ies (nome, local, media) values ('Weber, Dibbert and Kihn', 'Brazil', 21.61);
insert into ies (nome, local, media) values ('Marvin, Boyer and Kuhn', 'Brazil', 8.57);
insert into ies (nome, local, media) values ('Graham Group', 'Brazil', 42.69);
insert into ies (nome, local, media) values ('Hammes, Heller and Beier', 'Brazil', 61.66);
insert into ies (nome, local, media) values ('Shields-Cole', 'Brazil', 78.32);
insert into ies (nome, local, media) values ('Schowalter-Hackett', 'Brazil', 29.17);
insert into ies (nome, local, media) values ('Kovacek-Funk', 'Brazil', 57.96);
insert into ies (nome, local, media) values ('Schneider, Kub and Gorczany', 'Brazil', 64.73);
insert into ies (nome, local, media) values ('Hermann LLC', 'Brazil', 46.14);
insert into ies (nome, local, media) values ('McKenzie and Sons', 'Brazil', 68.2);
insert into ies (nome, local, media) values ('Osinski-Rice', 'Brazil', 61.69);
insert into ies (nome, local, media) values ('Monahan-Runolfsdottir', 'Brazil', 62.82);
insert into ies (nome, local, media) values ('Roberts-Schimmel', 'Brazil', 92.07);
insert into ies (nome, local, media) values ('Casper LLC', 'Brazil', 54.83);
insert into ies (nome, local, media) values ('Lowe LLC', 'Brazil', 25.85);
insert into ies (nome, local, media) values ('Donnelly, Keebler and Gorczany', 'Brazil', 81.75);
insert into ies (nome, local, media) values ('Abernathy Group', 'Brazil', 26.78);
insert into ies (nome, local, media) values ('Upton, MacGyver and Durgan', 'Brazil', 70.16);
insert into ies (nome, local, media) values ('Oberbrunner-Steuber', 'Brazil', 24.28);
insert into ies (nome, local, media) values ('Powlowski Group', 'Brazil', 48.13);
insert into ies (nome, local, media) values ('Mante Group', 'Brazil', 71.47);
insert into ies (nome, local, media) values ('Kihn, Effertz and Steuber', 'Brazil', 85.81);
insert into ies (nome, local, media) values ('Daugherty-Simonis', 'Brazil', 96.26);
insert into ies (nome, local, media) values ('Hayes, Schmitt and Lang', 'Brazil', 81.21);
insert into ies (nome, local, media) values ('Runolfsson, Olson and Medhurst', 'Brazil', 64.86);
insert into ies (nome, local, media) values ('Kshlerin, Thiel and Reinger', 'Brazil', 68.99);
insert into ies (nome, local, media) values ('Hettinger and Sons', 'Brazil', 44.79);
insert into ies (nome, local, media) values ('Kulas-Kuhlman', 'Brazil', 24.53);
insert into ies (nome, local, media) values ('Koelpin-Leuschke', 'Brazil', 28.39);
insert into ies (nome, local, media) values ('Carter-Jacobs', 'Brazil', 41.37);
insert into ies (nome, local, media) values ('Bradtke, Rau and Labadie', 'Brazil', 81.8);
insert into ies (nome, local, media) values ('Nitzsche, Hintz and Bahringer', 'Brazil', 65.84);
insert into ies (nome, local, media) values ('Effertz-Brown', 'Brazil', 48.82);
insert into ies (nome, local, media) values ('Braun Inc', 'Brazil', 94.02);
insert into ies (nome, local, media) values ('Corwin-Wilderman', 'Brazil', 28.64);
insert into ies (nome, local, media) values ('Kuhlman Inc', 'Brazil', 91.27);
insert into ies (nome, local, media) values ('Armstrong-Schroeder', 'Brazil', 47.64);
insert into ies (nome, local, media) values ('Leffler-Langosh', 'Brazil', 94.59);
insert into ies (nome, local, media) values ('Leffler, Runolfsson and Dicki', 'Brazil', 38.59);
insert into ies (nome, local, media) values ('Lueilwitz-Hodkiewicz', 'Brazil', 57.91);
insert into ies (nome, local, media) values ('Beahan Group', 'Brazil', 81.82);
insert into ies (nome, local, media) values ('Pagac, Batz and Dooley', 'Brazil', 37.48);
insert into ies (nome, local, media) values ('Koelpin, Schulist and Bernier', 'Brazil', 13.82);
insert into ies (nome, local, media) values ('Hagenes-Funk', 'Brazil', 11.34);
insert into ies (nome, local, media) values ('Wilkinson-Ratke', 'Brazil', 99.25);
insert into ies (nome, local, media) values ('Abshire, Hilll and Abbott', 'Brazil', 65.51);
insert into ies (nome, local, media) values ('McKenzie, Turcotte and Kiehn', 'Brazil', 42.68);
insert into ies (nome, local, media) values ('Cole and Sons', 'Brazil', 67.64);
insert into ies (nome, local, media) values ('Hickle-Prohaska', 'Brazil', 25.13);
insert into ies (nome, local, media) values ('Fadel-Morissette', 'Brazil', 97.34);
insert into ies (nome, local, media) values ('Brakus, Lowe and Breitenberg', 'Brazil', 89.37);
insert into ies (nome, local, media) values ('Hodkiewicz and Sons', 'Brazil', 27.33);
insert into ies (nome, local, media) values ('Orn, Carroll and Kub', 'Brazil', 89.54);
insert into ies (nome, local, media) values ('Grant, Rodriguez and Zemlak', 'Brazil', 81.47);
insert into ies (nome, local, media) values ('McGlynn-Bernhard', 'Brazil', 51.74);
insert into ies (nome, local, media) values ('Sporer, Satterfield and Johns', 'Brazil', 16.32);
insert into ies (nome, local, media) values ('Doyle, Bergstrom and Torphy', 'Brazil', 65.1);
insert into ies (nome, local, media) values ('Morissette, Renner and Schultz', 'Brazil', 22.16);
insert into ies (nome, local, media) values ('Kub-Shields', 'Brazil', 54.11);
insert into ies (nome, local, media) values ('Quigley, Dare and Tillman', 'Brazil', 64.75);
insert into ies (nome, local, media) values ('Adams Inc', 'Brazil', 65.73);
insert into ies (nome, local, media) values ('Fadel, Wisoky and Rath', 'Brazil', 68.29);
insert into ies (nome, local, media) values ('Feest, Sawayn and Rempel', 'Brazil', 66.93);
insert into ies (nome, local, media) values ('Prohaska and Sons', 'Brazil', 90.93);
insert into ies (nome, local, media) values ('Block, Monahan and Koelpin', 'Brazil', 14.01);
insert into ies (nome, local, media) values ('Haley, Hettinger and Mann', 'Brazil', 96.01);
insert into ies (nome, local, media) values ('Donnelly LLC', 'Brazil', 12.79);
insert into ies (nome, local, media) values ('Muller, Fahey and Botsford', 'Brazil', 88.12);
insert into ies (nome, local, media) values ('Cassin, Halvorson and Quitzon', 'Brazil', 23.28);
insert into ies (nome, local, media) values ('Kozey-Carroll', 'Brazil', 64.15);
insert into ies (nome, local, media) values ('Parker-Macejkovic', 'Brazil', 41.35);
insert into ies (nome, local, media) values ('Cruickshank-Shanahan', 'Brazil', 1.07);
insert into ies (nome, local, media) values ('Blanda Inc', 'Brazil', 48.34);
insert into ies (nome, local, media) values ('Olson, Swaniawski and Renner', 'Brazil', 60.91);
insert into ies (nome, local, media) values ('Balistreri Group', 'Brazil', 9.29);
insert into ies (nome, local, media) values ('Windler-Feest', 'Brazil', 68.29);
insert into ies (nome, local, media) values ('Bins-Nitzsche', 'Brazil', 10.04);
insert into ies (nome, local, media) values ('Tillman LLC', 'Brazil', 98.48);
insert into ies (nome, local, media) values ('Kuhlman, Treutel and Schulist', 'Brazil', 32.2);
insert into ies (nome, local, media) values ('Pfeffer Inc', 'Brazil', 12.57);
insert into ies (nome, local, media) values ('Dickinson and Sons', 'Brazil', 55.95);
insert into ies (nome, local, media) values ('Cassin, Welch and Macejkovic', 'Brazil', 9.93);
insert into ies (nome, local, media) values ('Veum, Gleason and Bergnaum', 'Brazil', 68.09);
insert into ies (nome, local, media) values ('Maggio, Weimann and Stokes', 'Brazil', 51.18);
insert into ies (nome, local, media) values ('Haag, Cruickshank and Nitzsche', 'Brazil', 9.44);
insert into ies (nome, local, media) values ('Witting-Terry', 'Brazil', 47.91);
insert into ies (nome, local, media) values ('Schaefer-Baumbach', 'Brazil', 95.61);
insert into ies (nome, local, media) values ('Lehner LLC', 'Brazil', 41.73);
insert into ies (nome, local, media) values ('Hoeger, Hand and Shields', 'Brazil', 34.37);
insert into ies (nome, local, media) values ('Effertz Inc', 'Brazil', 91.17);
insert into ies (nome, local, media) values ('Maggio Inc', 'Brazil', 44.91);
insert into ies (nome, local, media) values ('Torp, Donnelly and Hirthe', 'Brazil', 75.27);
insert into ies (nome, local, media) values ('Hegmann LLC', 'Brazil', 93.57);
insert into ies (nome, local, media) values ('Graham and Sons', 'Brazil', 90.81);
insert into ies (nome, local, media) values ('Quitzon Group', 'Brazil', 31.35);
insert into ies (nome, local, media) values ('Botsford Group', 'Brazil', 6.53);
insert into ies (nome, local, media) values ('Medhurst, Wintheiser and MacGyver', 'Brazil', 78.28);
insert into ies (nome, local, media) values ('Goyette Inc', 'Brazil', 25.3);
insert into ies (nome, local, media) values ('Swift and Sons', 'Brazil', 43.41);
insert into ies (nome, local, media) values ('Bechtelar Group', 'Brazil', 42.52);
insert into ies (nome, local, media) values ('Pouros Inc', 'Brazil', 87.19);
insert into ies (nome, local, media) values ('Weber-Heller', 'Brazil', 70.25);
insert into ies (nome, local, media) values ('Cartwright-Konopelski', 'Brazil', 44.22);
insert into ies (nome, local, media) values ('Smitham-Braun', 'Brazil', 31.34);
insert into ies (nome, local, media) values ('Tremblay and Sons', 'Brazil', 44.13);
insert into ies (nome, local, media) values ('Hoeger-Kutch', 'Brazil', 94.36);
insert into ies (nome, local, media) values ('Bartell-Osinski', 'Brazil', 33.85);
insert into ies (nome, local, media) values ('Heathcote, Spinka and Schmitt', 'Brazil', 61.43);
insert into ies (nome, local, media) values ('Hamill-Steuber', 'Brazil', 21.38);
insert into ies (nome, local, media) values ('Rogahn-Greenfelder', 'Brazil', 36.89);
insert into ies (nome, local, media) values ('Zieme Inc', 'Brazil', 89.38);
insert into ies (nome, local, media) values ('Pouros, Collier and Wisoky', 'Brazil', 58.1);
insert into ies (nome, local, media) values ('Fay Group', 'Brazil', 70.58);
insert into ies (nome, local, media) values ('Tremblay, Schimmel and MacGyver', 'Brazil', 86.68);
insert into ies (nome, local, media) values ('Lindgren, McDermott and Nikolaus', 'Brazil', 86.24);
insert into ies (nome, local, media) values ('Towne-Von', 'Brazil', 68.66);
insert into ies (nome, local, media) values ('Prosacco, Schmeler and Fahey', 'Brazil', 55.48);
insert into ies (nome, local, media) values ('Schmidt-Jacobs', 'Brazil', 69.11);
insert into ies (nome, local, media) values ('Cronin Group', 'Brazil', 94.85);
insert into ies (nome, local, media) values ('Jaskolski, Nitzsche and Daniel', 'Brazil', 29.99);
insert into ies (nome, local, media) values ('O''Hara, Berge and Johnston', 'Brazil', 15.97);
insert into ies (nome, local, media) values ('Leuschke and Sons', 'Brazil', 10.23);
insert into ies (nome, local, media) values ('Lang Inc', 'Brazil', 12.94);
insert into ies (nome, local, media) values ('Spinka-Friesen', 'Brazil', 93.2);
insert into ies (nome, local, media) values ('Beahan, Monahan and Lind', 'Brazil', 95.97);
insert into ies (nome, local, media) values ('Pagac-Streich', 'Brazil', 21.11);
insert into ies (nome, local, media) values ('Daugherty-Cremin', 'Brazil', 84.68);
insert into ies (nome, local, media) values ('Keebler, Nienow and Spencer', 'Brazil', 41.81);
insert into ies (nome, local, media) values ('Glover Group', 'Brazil', 38.95);
insert into ies (nome, local, media) values ('Jacobi Inc', 'Brazil', 98.55);
insert into ies (nome, local, media) values ('Reichert-Morissette', 'Brazil', 34.92);
insert into ies (nome, local, media) values ('Lemke Group', 'Brazil', 67.61);
insert into ies (nome, local, media) values ('Wintheiser, Keeling and Gutkowski', 'Brazil', 56.11);
insert into ies (nome, local, media) values ('Wolf Inc', 'Brazil', 25.41);
insert into ies (nome, local, media) values ('Gutkowski-Anderson', 'Brazil', 85.34);
insert into ies (nome, local, media) values ('Murazik Group', 'Brazil', 27.89);
insert into ies (nome, local, media) values ('Bartoletti Group', 'Brazil', 45.2);
insert into ies (nome, local, media) values ('Stroman, Roberts and Kshlerin', 'Brazil', 23.76);
insert into ies (nome, local, media) values ('Ritchie Group', 'Brazil', 80.86);
insert into ies (nome, local, media) values ('Lang, DuBuque and Lebsack', 'Brazil', 2.11);
insert into ies (nome, local, media) values ('Mills and Sons', 'Brazil', 67.72);
insert into ies (nome, local, media) values ('Swaniawski, Schowalter and Grady', 'Brazil', 69.18);
insert into ies (nome, local, media) values ('Marquardt-Smith', 'Brazil', 30.59);
insert into ies (nome, local, media) values ('Rempel-Nitzsche', 'Brazil', 13.96);
insert into ies (nome, local, media) values ('Leuschke-Kris', 'Brazil', 89.06);
insert into ies (nome, local, media) values ('Heller, Torphy and Gutmann', 'Brazil', 78.53);
insert into ies (nome, local, media) values ('Boyer, Simonis and Kub', 'Brazil', 30.25);
insert into ies (nome, local, media) values ('Bayer-Rippin', 'Brazil', 21.11);
insert into ies (nome, local, media) values ('Abernathy, Brown and Hamill', 'Brazil', 15.78);
insert into ies (nome, local, media) values ('Christiansen-Von', 'Brazil', 13.26);
insert into ies (nome, local, media) values ('Daugherty, Torp and Oberbrunner', 'Brazil', 36.81);
insert into ies (nome, local, media) values ('Ruecker, Nader and VonRueden', 'Brazil', 74.96);
insert into ies (nome, local, media) values ('Wisozk-Hayes', 'Brazil', 8.64);
insert into ies (nome, local, media) values ('Gaylord-Reinger', 'Brazil', 79.9);
insert into ies (nome, local, media) values ('Donnelly Group', 'Brazil', 22.33);
insert into ies (nome, local, media) values ('MacGyver-Krajcik', 'Brazil', 75.31);
insert into ies (nome, local, media) values ('Kertzmann Group', 'Brazil', 5.21);
insert into ies (nome, local, media) values ('Cartwright and Sons', 'Brazil', 94.24);
insert into ies (nome, local, media) values ('Howell and Sons', 'Brazil', 86.72);
insert into ies (nome, local, media) values ('Kub-Anderson', 'Brazil', 10.57);
insert into ies (nome, local, media) values ('Pacocha-Strosin', 'Brazil', 30.46);
insert into ies (nome, local, media) values ('Heaney-Watsica', 'Brazil', 80.91);
insert into ies (nome, local, media) values ('Lakin-Dibbert', 'Brazil', 41.65);
insert into ies (nome, local, media) values ('Romaguera, Keebler and White', 'Brazil', 69.32);
insert into ies (nome, local, media) values ('Ward-Okuneva', 'Brazil', 37.72);
insert into ies (nome, local, media) values ('Schultz, Hartmann and Fadel', 'Brazil', 38.98);
insert into ies (nome, local, media) values ('Veum-Prosacco', 'Brazil', 9.04);
insert into ies (nome, local, media) values ('Funk-Schmidt', 'Brazil', 87.49);
insert into ies (nome, local, media) values ('Hilpert, Reynolds and Hane', 'Brazil', 67.46);
insert into ies (nome, local, media) values ('Wilkinson-Bins', 'Brazil', 8.2);
insert into ies (nome, local, media) values ('Gibson, Jerde and Crona', 'Brazil', 11.29);
insert into ies (nome, local, media) values ('Schultz Group', 'Brazil', 3.55);
insert into ies (nome, local, media) values ('Gusikowski-Wintheiser', 'Brazil', 59.33);
insert into ies (nome, local, media) values ('Smitham-Wintheiser', 'Brazil', 21.84);
insert into ies (nome, local, media) values ('Welch, Moen and Sipes', 'Brazil', 73.76);
insert into ies (nome, local, media) values ('Simonis Group', 'Brazil', 4.76);
insert into ies (nome, local, media) values ('Glover, Bogisich and Ullrich', 'Brazil', 10.02);
insert into ies (nome, local, media) values ('Kutch-Will', 'Brazil', 57.34);
insert into ies (nome, local, media) values ('Reilly, Konopelski and Farrell', 'Brazil', 13.24);
insert into ies (nome, local, media) values ('Anderson and Sons', 'Brazil', 72.98);
insert into ies (nome, local, media) values ('Ankunding Group', 'Brazil', 23.2);
insert into ies (nome, local, media) values ('Cummerata Group', 'Brazil', 34.46);
insert into ies (nome, local, media) values ('Lueilwitz-Wintheiser', 'Brazil', 41.85);
insert into ies (nome, local, media) values ('Stracke Group', 'Brazil', 64.79);
insert into ies (nome, local, media) values ('Gutmann-Quigley', 'Brazil', 51.78);
insert into ies (nome, local, media) values ('Jacobson Inc', 'Brazil', 10.09);
insert into ies (nome, local, media) values ('Kohler LLC', 'Brazil', 90.52);
insert into ies (nome, local, media) values ('McCullough LLC', 'Brazil', 41.79);
insert into ies (nome, local, media) values ('Williamson-Rau', 'Brazil', 18.16);
insert into ies (nome, local, media) values ('Yost-Stamm', 'Brazil', 27.66);
insert into ies (nome, local, media) values ('Reinger, Strosin and Watsica', 'Brazil', 75.24);
insert into ies (nome, local, media) values ('Kovacek and Sons', 'Brazil', 83.23);
insert into ies (nome, local, media) values ('Langosh, Botsford and Veum', 'Brazil', 7.44);
insert into ies (nome, local, media) values ('Tromp-Rempel', 'Brazil', 14.42);
insert into ies (nome, local, media) values ('Swift-Lynch', 'Brazil', 68.79);
insert into ies (nome, local, media) values ('Welch and Sons', 'Brazil', 54.89);
insert into ies (nome, local, media) values ('Langosh-Kiehn', 'Brazil', 28.67);
insert into ies (nome, local, media) values ('Hermann, Graham and Durgan', 'Brazil', 11.21);
insert into ies (nome, local, media) values ('Wilkinson Group', 'Brazil', 92.19);
insert into ies (nome, local, media) values ('Hoppe-Moen', 'Brazil', 45.41);
insert into ies (nome, local, media) values ('Lubowitz Group', 'Brazil', 20.41);
insert into ies (nome, local, media) values ('Schiller-Hyatt', 'Brazil', 41.8);
insert into ies (nome, local, media) values ('Mayer and Sons', 'Brazil', 32.93);
insert into ies (nome, local, media) values ('Kling-Sauer', 'Brazil', 15.61);
insert into ies (nome, local, media) values ('Abshire-Hackett', 'Brazil', 30.54);
insert into ies (nome, local, media) values ('Fay-Kiehn', 'Brazil', 83.92);
insert into ies (nome, local, media) values ('Doyle and Sons', 'Brazil', 35.42);
insert into ies (nome, local, media) values ('Deckow Inc', 'Brazil', 31.54);
insert into ies (nome, local, media) values ('Schulist Group', 'Brazil', 79.2);
insert into ies (nome, local, media) values ('Douglas Inc', 'Brazil', 29.01);
insert into ies (nome, local, media) values ('Lesch Group', 'Brazil', 13.93);
insert into ies (nome, local, media) values ('Greenholt Group', 'Brazil', 22.44);
insert into ies (nome, local, media) values ('Nader LLC', 'Brazil', 58.99);
insert into ies (nome, local, media) values ('Effertz Group', 'Brazil', 86.91);
insert into ies (nome, local, media) values ('Mann LLC', 'Brazil', 28.58);
insert into ies (nome, local, media) values ('Zulauf-Turcotte', 'Brazil', 31.21);
insert into ies (nome, local, media) values ('Bernhard, Metz and Haley', 'Brazil', 72.63);
insert into ies (nome, local, media) values ('Reichert Group', 'Brazil', 49.46);
insert into ies (nome, local, media) values ('Weimann Inc', 'Brazil', 97.37);
insert into ies (nome, local, media) values ('Reilly LLC', 'Brazil', 21.95);
insert into ies (nome, local, media) values ('Bergnaum-Mayer', 'Brazil', 14.56);
insert into ies (nome, local, media) values ('Collins, Dicki and Hickle', 'Brazil', 70.08);
insert into ies (nome, local, media) values ('Fay LLC', 'Brazil', 18.03);
insert into ies (nome, local, media) values ('Sauer, Schneider and Predovic', 'Brazil', 97.21);
insert into ies (nome, local, media) values ('Beatty-Reichert', 'Brazil', 35.21);
insert into ies (nome, local, media) values ('Bayer, Dooley and Hoeger', 'Brazil', 66.5);
insert into ies (nome, local, media) values ('Kutch, Cassin and Jenkins', 'Brazil', 4.37);
insert into ies (nome, local, media) values ('Ruecker-McClure', 'Brazil', 46.22);
insert into ies (nome, local, media) values ('Schulist LLC', 'Brazil', 29.87);
insert into ies (nome, local, media) values ('Padberg-Emard', 'Brazil', 95.27);
insert into ies (nome, local, media) values ('Jacobson Group', 'Brazil', 84.2);
insert into ies (nome, local, media) values ('Zemlak-Weber', 'Brazil', 12.84);
insert into ies (nome, local, media) values ('Shields, Kiehn and Beier', 'Brazil', 82.24);
insert into ies (nome, local, media) values ('Littel-Kuhic', 'Brazil', 59.98);
insert into ies (nome, local, media) values ('Labadie, Daugherty and Champlin', 'Brazil', 49.72);
insert into ies (nome, local, media) values ('Klein and Sons', 'Brazil', 46.69);
insert into ies (nome, local, media) values ('Mitchell, Smith and Eichmann', 'Brazil', 92.42);
insert into ies (nome, local, media) values ('Wolf Inc', 'Brazil', 7.42);
insert into ies (nome, local, media) values ('Daniel-Carter', 'Brazil', 91.14);
insert into ies (nome, local, media) values ('Paucek and Sons', 'Brazil', 94.43);
insert into ies (nome, local, media) values ('Sawayn Inc', 'Brazil', 28.45);
insert into ies (nome, local, media) values ('Bogan LLC', 'Brazil', 11.81);
insert into ies (nome, local, media) values ('Connelly-Quigley', 'Brazil', 90.38);
insert into ies (nome, local, media) values ('Collier Inc', 'Brazil', 3.14);
insert into ies (nome, local, media) values ('Pfannerstill, Glover and Steuber', 'Brazil', 51.28);
insert into ies (nome, local, media) values ('Bahringer-Veum', 'Brazil', 61.62);
insert into ies (nome, local, media) values ('Walsh-Dach', 'Brazil', 78.48);
insert into ies (nome, local, media) values ('Crona LLC', 'Brazil', 93.17);
insert into ies (nome, local, media) values ('Dickens Group', 'Brazil', 11.11);
insert into ies (nome, local, media) values ('Breitenberg Group', 'Brazil', 22.2);
insert into ies (nome, local, media) values ('Stiedemann, Bernier and Beahan', 'Brazil', 1.99);
insert into ies (nome, local, media) values ('Steuber Group', 'Brazil', 67.69);
insert into ies (nome, local, media) values ('Haley-Upton', 'Brazil', 77.96);
insert into ies (nome, local, media) values ('Hilll-Hirthe', 'Brazil', 71.27);
insert into ies (nome, local, media) values ('Smitham-Gutkowski', 'Brazil', 74.98);
insert into ies (nome, local, media) values ('Von-Torp', 'Brazil', 5.37);
insert into ies (nome, local, media) values ('Marquardt-Heller', 'Brazil', 93.62);
insert into ies (nome, local, media) values ('Zemlak-Windler', 'Brazil', 89.3);
insert into ies (nome, local, media) values ('Bernhard, Runolfsson and Auer', 'Brazil', 48.78);
insert into ies (nome, local, media) values ('Reilly and Sons', 'Brazil', 4.2);
insert into ies (nome, local, media) values ('Balistreri, Bartoletti and Morissette', 'Brazil', 89.93);
insert into ies (nome, local, media) values ('Mitchell Group', 'Brazil', 59.48);
insert into ies (nome, local, media) values ('Smith-Weimann', 'Brazil', 6.96);
insert into ies (nome, local, media) values ('Frami, Koss and Beahan', 'Brazil', 24.1);
insert into ies (nome, local, media) values ('Padberg, Heaney and Walsh', 'Brazil', 69.8);
insert into ies (nome, local, media) values ('Labadie-Boyer', 'Brazil', 62.55);
insert into ies (nome, local, media) values ('Gleason LLC', 'Brazil', 5.64);
insert into ies (nome, local, media) values ('Bogan Group', 'Brazil', 28.11);
insert into ies (nome, local, media) values ('Ledner, Hyatt and Hegmann', 'Brazil', 69.03);
insert into ies (nome, local, media) values ('Koelpin-Schamberger', 'Brazil', 34.89);
insert into ies (nome, local, media) values ('Corwin, Schuppe and Swift', 'Brazil', 58.85);
insert into ies (nome, local, media) values ('Bayer and Sons', 'Brazil', 49.77);
insert into ies (nome, local, media) values ('Ortiz, Howe and Aufderhar', 'Brazil', 73.7);
insert into ies (nome, local, media) values ('Stehr Inc', 'Brazil', 30.86);
insert into ies (nome, local, media) values ('Gerlach, O''Hara and Hoppe', 'Brazil', 25.09);
insert into ies (nome, local, media) values ('Lockman Group', 'Brazil', 59.72);
insert into ies (nome, local, media) values ('Heaney-Shields', 'Brazil', 40.63);
insert into ies (nome, local, media) values ('Jacobs LLC', 'Brazil', 70.49);
insert into ies (nome, local, media) values ('Huel, Herman and Legros', 'Brazil', 48.88);
insert into ies (nome, local, media) values ('McKenzie, Waelchi and Lakin', 'Brazil', 64.74);
insert into ies (nome, local, media) values ('Wehner, Dare and Gutkowski', 'Brazil', 8.42);
insert into ies (nome, local, media) values ('Harber, Hoppe and Huels', 'Brazil', 32.33);
insert into ies (nome, local, media) values ('Klocko-Lemke', 'Brazil', 41.32);
insert into ies (nome, local, media) values ('Larson and Sons', 'Brazil', 51.52);
insert into ies (nome, local, media) values ('Huels and Sons', 'Brazil', 3.75);
insert into ies (nome, local, media) values ('Crooks, O''Kon and Balistreri', 'Brazil', 83.26);
insert into ies (nome, local, media) values ('Fay, Kunde and Boyle', 'Brazil', 25.93);
insert into ies (nome, local, media) values ('Cruickshank-Barton', 'Brazil', 15.17);
insert into ies (nome, local, media) values ('Langosh, Walsh and Hayes', 'Brazil', 90.72);
insert into ies (nome, local, media) values ('Reichert-Blanda', 'Brazil', 68.3);
insert into ies (nome, local, media) values ('Witting Group', 'Brazil', 75.86);
insert into ies (nome, local, media) values ('Davis, Veum and Lind', 'Brazil', 86.13);
insert into ies (nome, local, media) values ('Willms-Bernhard', 'Brazil', 6.02);
insert into ies (nome, local, media) values ('Auer and Sons', 'Brazil', 62.39);
insert into ies (nome, local, media) values ('Nitzsche-O''Conner', 'Brazil', 8.85);
insert into ies (nome, local, media) values ('Kris-Swift', 'Brazil', 94.09);
insert into ies (nome, local, media) values ('Doyle LLC', 'Brazil', 45.84);
insert into ies (nome, local, media) values ('Pfeffer-Braun', 'Brazil', 14.52);
insert into ies (nome, local, media) values ('Lubowitz, Kreiger and Moore', 'Brazil', 98.74);
insert into ies (nome, local, media) values ('Will-Boyle', 'Brazil', 34.16);
insert into ies (nome, local, media) values ('Bernhard-Cole', 'Brazil', 89.7);
insert into ies (nome, local, media) values ('Bosco and Sons', 'Brazil', 26.45);
insert into ies (nome, local, media) values ('Sipes, Deckow and Jones', 'Brazil', 53.52);
insert into ies (nome, local, media) values ('Roob Inc', 'Brazil', 59.42);
insert into ies (nome, local, media) values ('Romaguera-Russel', 'Brazil', 2.43);
insert into ies (nome, local, media) values ('Watsica-Mohr', 'Brazil', 20.16);
insert into ies (nome, local, media) values ('Powlowski LLC', 'Brazil', 77.02);
insert into ies (nome, local, media) values ('Murphy, Kiehn and Anderson', 'Brazil', 14.08);
insert into ies (nome, local, media) values ('Gislason, Rempel and Lubowitz', 'Brazil', 38.89);
insert into ies (nome, local, media) values ('Botsford, Haley and Harris', 'Brazil', 53.21);
insert into ies (nome, local, media) values ('Casper and Sons', 'Brazil', 28.4);
insert into ies (nome, local, media) values ('McClure-Hauck', 'Brazil', 48.29);
insert into ies (nome, local, media) values ('Welch and Sons', 'Brazil', 70.42);
insert into ies (nome, local, media) values ('Turcotte, Armstrong and Marvin', 'Brazil', 1.06);
insert into ies (nome, local, media) values ('Ziemann, Gottlieb and Prosacco', 'Brazil', 96.18);
insert into ies (nome, local, media) values ('Daniel-Mraz', 'Brazil', 65.56);
insert into ies (nome, local, media) values ('Sanford Inc', 'Brazil', 44.14);
insert into ies (nome, local, media) values ('Wehner-Littel', 'Brazil', 45.63);
insert into ies (nome, local, media) values ('Greenfelder-Bailey', 'Brazil', 13.74);
insert into ies (nome, local, media) values ('DuBuque, Dietrich and Braun', 'Brazil', 60.83);
insert into ies (nome, local, media) values ('Hackett, Kutch and Mayert', 'Brazil', 52.63);
insert into ies (nome, local, media) values ('Lang Group', 'Brazil', 44.24);
insert into ies (nome, local, media) values ('Ankunding Group', 'Brazil', 6.25);
insert into ies (nome, local, media) values ('Lakin and Sons', 'Brazil', 17.04);
insert into ies (nome, local, media) values ('Douglas Inc', 'Brazil', 20.32);
insert into ies (nome, local, media) values ('Harvey LLC', 'Brazil', 6.18);
insert into ies (nome, local, media) values ('Emmerich Inc', 'Brazil', 81.43);
insert into ies (nome, local, media) values ('Zboncak-Barton', 'Brazil', 35.91);
insert into ies (nome, local, media) values ('Effertz Group', 'Brazil', 39.52);
insert into ies (nome, local, media) values ('Jenkins, Mann and Daugherty', 'Brazil', 5.64);
